version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"

    reviewers:
      - "RuminantFarmSystems/dev-team"

    labels:
      - "dependencies"