import re
from typing import Dict, List, Any, Callable, Collection
from RUFAS.graph_generator import GraphGenerator
from RUFAS.util import Utility


def average_aggregator(data: List[float]) -> float:
    """
    Calculates the average of a list of numbers.

    Parameters
    ----------
    data : List[float]
        A list of numbers whose average is to be calculated.

    Returns
    -------
    float
        The average of the input numbers.
    """
    return sum(data) / len(data) if data else 0


def division_aggregator(data: List[float]) -> float:
    """
    Divides the first number in the list by each of the subsequent numbers.

    Parameters
    ----------
    data : List[float]
        A list of numbers for the division operation.

    Returns
    -------
    float
        The result of dividing the first number by each subsequent number.
        Returns None if the list is empty or has only one element.
    """
    if len(data) < 2:
        return None
    result = data[0]
    for num in data[1:]:
        if num == 0:  # Avoid division by zero
            return None
        result /= num
    return result


def product_aggregator(data: List[float]) -> float:
    """
    Returns the product of a list of numbers.

    Parameters
    ----------
    data : List[float]
        A list of numbers whose product is to be calculated.

    Returns
    -------
    float
        The product of the input numbers. Returns 1 for an empty list.
    """
    product = 1
    for num in data:
        product *= num
    return product


def sd_aggregator(data: List[float]) -> float:
    """
    Calculates the standard deviation of a list of numbers.

    Parameters
    ----------
    data : List[float]
        A list of numbers whose standard deviation is to be calculated.

    Returns
    -------
    float
        The standard deviation of the input numbers.
    """
    mean = average_aggregator(data)
    return (sum((x - mean) ** 2 for x in data) / len(data)) ** 0.5 if data else 0


def sum_aggregator(data: List[float]) -> float:
    """
    Returns the sum of a list of numbers.

    Parameters
    ----------
    data : List[float]
        A list of numbers whose sum is to be calculated.

    Returns
    -------
    float
        The sum of the input numbers.
    """
    return sum(data)


def subtraction_aggregator(data: List[float]) -> float:
    """
    Subtracts each subsequent number in the list from the first number.

    Parameters
    ----------
    data : List[float]
        A list of numbers for the subtraction operation.

    Returns
    -------
    float
        The result of subtracting each subsequent number from the first number.
        Returns None if the list is empty or has only one element.
    """
    if len(data) < 2:
        return None
    result = data[0]
    for num in data[1:]:
        result -= num
    return result


AGGREGATION_FUNCTIONS: Dict[str, Callable[[List[float]], float]] = {
    "average": average_aggregator,
    "division": division_aggregator,
    "product": product_aggregator,
    "SD": sd_aggregator,
    "sum": sum_aggregator,
    "subtraction": subtraction_aggregator,
}


class ReportGenerator:
    """
    A class to generate reports based on filtered data and aggregation criteria and store them in a dictionary.

    Attributes
    ----------
    reports : Dict[str, Dict[str, List[Any]]]
        A dictionary containing the generated reports, with the report name as the key and the report data as the value.
    time : Time | None
        A Time object used to track the simulation time
    """

    def __init__(self, time=None) -> None:
        """
        Initializes the ReportGenerator.
        """

        self.reports: Dict[str, Dict[str, List[Any]]] = {}
        self.time = time

    def clear_reports(self) -> None:
        """
        Clears the reports generated by the ReportGenerator.

        Returns
        -------
        None
        """

        self.reports = {}

    def generate_report(
        self,
        filter_content: Dict[str, Any],
        filtered_pool: Dict[str, Dict[str, List[Any]]],
    ) -> List[Dict[str, str | Dict[str, str]]]:
        """
        Generates a report specified by the given filter content.

        Parameters
        ----------
        filter_content : Dict[str, Any]
            A dictionary containing the configuration for the report, including details
            such as 'name', 'filters', 'cross_references', and aggregation instructions.

        filtered_pool : Dict[str, Dict[str, List[Any]]]
            The data pool from which reports are generated.

        Returns
        -------
        List[Dict[str, str | Dict[str, str]]]
            A list of log events.
        """

        event_logs: List[Dict[str, str | Dict[str, str]]] = []
        info_map = {
            "class": self.__class__.__name__,
            "function": self.generate_report.__name__,
        }

        individual_report_name = self._ensure_unique_report_name_with_timestamp(filter_content.get("name"))

        init_event_log = {
            "log": "start_generate_individual_report",
            "message": f"Start generating individual report: {individual_report_name}",
            "info_map": info_map,
        }
        event_logs.append(init_event_log)

        try:
            report_filter_data = {}
            if "cross_references" in filter_content.keys():
                self._check_for_missing_references(filter_content["cross_references"])
                cross_reference_data = self._get_reports_by_regex(filter_content["cross_references"])
                cross_reference_data.update(filtered_pool)
                report_data = self._perform_aggregations(cross_reference_data, filter_content)
            else:
                report_data = self._perform_aggregations(filtered_pool, filter_content)
            should_graph_report_data = filter_content.get("graph_details")
            enable_graph_and_report = filter_content.get("graph_and_report", False)
            for col, values in report_data.items():
                column_name = self._ensure_unique_report_name_with_timestamp(
                    f"{individual_report_name}_{col}" if len(individual_report_name) > 0 else col
                )
                report_filter_data[column_name] = {"values": values}
            if should_graph_report_data:
                if enable_graph_and_report:
                    self.reports.update(report_filter_data)
                graph_event_log = self._prepare_report_data_to_be_graphed(
                    report_filter_data, filter_content, individual_report_name
                )
                event_logs.extend(graph_event_log)
            elif not should_graph_report_data:
                self.reports.update(report_filter_data)
                report_filter_data = {}
                if enable_graph_and_report:
                    warning_event_log = {
                        "warning": "report_generation_warning",
                        "message": "Request to graph and report data not fulfilled "
                        "- no graph_details present in report filter file.",
                        "info_map": info_map,
                    }
                    event_logs.append(warning_event_log)

        except (KeyError, ValueError) as e:
            error_type = e.__class__.__name__
            error_event_log = {
                "error": "report_generation_error",
                "message": f"Error generating the individual report ({individual_report_name}) => {error_type}: {e}",
                "info_map": info_map,
            }
            event_logs.append(error_event_log)

        return event_logs

    def _get_horizontal_first_value(
        self,
        filter_content: Dict[str, Any],
    ) -> bool:
        """
        Check if the 'horizontal_first' property (when present) in the report filter is a boolean.
        If not, raise an error. Return the value of 'horizontal_first' or False as the default value.

        Parameters
        ----------
        filter_content : Dict[str, Any]
            A dictionary containing the configuration for the report, including details such as 'name', 'filters',
            'cross_references', and aggregation instructions.

        Returns
        -------
        bool
            The value of 'horizontal_first' in the report filter, or False if it is not present.

        Raises
        ------
        ValueError
            If the value of 'horizontal_first' in the report filter is not a boolean.
        """

        if "horizontal_first" not in filter_content:
            return False

        horizontal_first = filter_content["horizontal_first"]

        if not isinstance(horizontal_first, bool):
            raise ValueError(
                f"The value of 'horizontal_first' in the report filter should be a boolean. "
                f"Value provided: {repr(filter_content['horizontal_first'])} "
                f"(type {type(filter_content['horizontal_first'])})"
            )

        return horizontal_first

    def _prepare_report_data_to_be_graphed(
        self, graph_data: Dict[str, Any], filter_content: Dict[str, Any], individual_report_name: str
    ) -> List[Dict[str, str | Dict[str, str]]] | List[Dict[str, Collection[str]]]:
        """Prepare and send aggregated report data to Graph Generator to be graphed.
        Parameters
        ----------
        graph_data : Dict[str, Any]
            The report data to be graphed.
        filter_content : Dict[str, Any]
            A dictionary containing the configuration for the report, including details
            such as 'name', 'filters', 'cross_references', and aggregation instructions.
        individual_report_name : str
            The name of the report to be graphed.

        Returns
        -------
        List[Dict[str, str | Dict[str, str]]] | List[Dict[str, Collection[str]]]
            Returns the logs from GraphGenerator.generate_graph()
        """

        graph_generator = GraphGenerator(filter_content["graph_details"]["metadata_prefix"])
        graph_details = {
            **filter_content["graph_details"],
            "title": filter_content["name"],
            "filters": filter_content["filters"],
        }
        graphics_dir = graph_details.pop("graphics_dir", None)
        produce_graphics = graph_details.get("produce_graphics")
        graph_event_log = graph_generator.generate_graph(
            graph_data, graph_details, individual_report_name, graphics_dir, produce_graphics
        )
        return graph_event_log

    def _ensure_unique_report_name_with_timestamp(self, report_name: str | None) -> str:
        """
        Make the given report name unique, if it is not, by appending a timestamp to it.

        Notes
        -----
        The rules for generating the name are as follows:
        1. If the report name is None, the name is set to `untitled_<timestamp>`.
        2. If the name is not a string, it is converted to a string.
        3. If the name is already present in the list of previously generated reports, the timestamp is appended
            to the name to make it unique.
        4. Otherwise, return the report name as is.

        Parameters
        ----------
        report_name : str | None
            The name of the report.

        Returns
        -------
        str
            The unique name for the report.
        """

        if report_name is None:
            report_name = f"untitled_{Utility.get_timestamp(True)}"

        if report_name in self.reports:
            report_name = f"{report_name}_{Utility.get_timestamp(True)}"

        return report_name

    def _check_for_missing_references(self, references: List[str]) -> None:
        """
        Checks if all the referenced reports are present in the list of previously generated reports.

        Parameters
        ----------
        references : List[str]
            The list of report references to check.

        Raises
        ------
        KeyError
            If any of the report references are missing.
        """

        missing_references = []

        for ref in references:
            if not any(re.fullmatch(ref, report_name) for report_name in self.reports):
                missing_references.append(ref)

        if missing_references:
            raise KeyError(
                f"Missing referenced reports matching the following pattern(s): {', '.join(missing_references)}"
            )

    def _get_reports_by_regex(self, regex_patterns: List[str]) -> Dict[str, Dict[str, List[Any]]]:
        """
        Retrieve reports based on matching the existing report names with the given regex patterns.

        Notes
        -----
        Each pattern is checked for a full match against the report names. A "full match"
        means that the regex must match the entire string of the report name from start to finish,
        without partial matches. This reduces the potential for false positives.

        Parameters
        ----------
        regex_patterns : List[str]
            A list of regex patterns to match with the existing report names.
        """

        matched_reports = {}
        for pattern in regex_patterns:
            for report_name in self.reports:
                if re.fullmatch(pattern, report_name):
                    matched_reports[report_name] = self.reports[report_name]
        return matched_reports

    def _perform_aggregations(
        self,
        filtered_pool: Dict[str, Dict[str, List[Any]]],
        filter_content: Dict[str, Any],
    ) -> Dict[str, List[float]]:
        """
        Fetches aggregation keys from the filter content and applies aggregation to the data.

        Parameters
        ----------
        filtered_pool : Dict[str, Dict[str, List[Any]]]
            The data pool from which the report is to be generated, structured as a dictionary.
        filter_content : Dict[str, Any]
            A dictionary containing filter criteria, aggregation instructions, and scalar operation details.

        Returns
        -------
        Dict[str, List[Any]]
            If no aggregation is specified, all the columns will be returned.
            If both horizontal and vertical aggregations are specified, the returned dictionary will have one key
                that is either "hor_ver_agg" or "ver_hor_agg" depending on the value of the "horizontal_first" key
                in the filter content.
            If only horizontal aggregation is specified, the returned dictionary will have one key "hor_agg".
            If only vertical aggregation is specified, the returned dictionary will have one key "ver_agg".

        Raises
        ------
        ValueError
            If there is an error preparing the report data.
            If the report data is empty.
            If the type of horizontal or vertical aggregation is not supported.
        """

        try:
            (
                horizontal_agg_key,
                vertical_agg_key,
            ) = self._extract_and_check_aggregation_keys(filter_content)
            report_data: Dict[str, List[Any]] = {key: filtered_pool[key]["values"] for key in filtered_pool.keys()}
            if not all(report_data[key] for key in report_data.keys()):
                raise ValueError
            self._add_constants_to_report_data(report_data, filter_content)
        except ValueError:
            raise

        if not report_data:
            raise ValueError(
                f"filter {filter_content.get('filters')} in {filter_content.get('name')} led to empty report data."
            )

        if not horizontal_agg_key and not vertical_agg_key:
            return report_data

        aggregate_report = report_data

        if horizontal_agg_key and vertical_agg_key:
            aggregate_report = self._handle_horizontal_and_vertical_aggregations(
                aggregate_report, horizontal_agg_key, vertical_agg_key, filter_content
            )

        elif horizontal_agg_key:
            horizontal_aggregator = AGGREGATION_FUNCTIONS[horizontal_agg_key]
            loop_list = filter_content.get("horizontal_order", list(aggregate_report.keys()))
            horizontally_aggregated = self._apply_horizontal_aggregation(
                aggregate_report, loop_list, horizontal_aggregator
            )
            aggregate_report = {"hor_agg": horizontally_aggregated}

        elif vertical_agg_key:
            vertical_aggregator = AGGREGATION_FUNCTIONS[vertical_agg_key]
            vertically_aggregated = self._apply_vertical_aggregation(aggregate_report, vertical_aggregator)

            has_dict_variables = filter_content.get("variables") is not None
            has_multiple_columns = len(vertically_aggregated) > 1

            if has_dict_variables or has_multiple_columns:
                aggregate_report = {f"{key}_ver_agg": value for key, value in vertically_aggregated.items()}
            else:
                aggregate_report = {"ver_agg": list(vertically_aggregated.values())[0]}

        return aggregate_report

    def _handle_horizontal_and_vertical_aggregations(
        self,
        aggregate_report: Dict[str, List[Any]],
        horizontal_agg_key: str,
        vertical_agg_key: str,
        filter_content: Dict[str, Any],
    ) -> Dict[str, List[Any]]:
        """
        Handles both horizontal and vertical aggregations on the report data.

        Parameters
        ----------
        aggregate_report : Dict[str, List[Any]]
            The report data to be aggregated.
        horizontal_agg_key : str
            The key for the horizontal aggregation function.
        vertical_agg_key : str
            The key for the vertical aggregation function.
        filter_content : Dict[str, Any]
            A dictionary containing filter criteria, aggregation instructions, and scalar operation details.

        Returns
        -------
        Dict[str, List[Any]]
            The aggregated report data.
        """

        horizontal_first = self._get_horizontal_first_value(filter_content)
        horizontal_aggregator = AGGREGATION_FUNCTIONS[horizontal_agg_key]
        vertical_aggregator = AGGREGATION_FUNCTIONS[vertical_agg_key]
        if horizontal_first:
            loop_list = filter_content.get("horizontal_order", list(aggregate_report.keys()))
            horizontally_aggregated = self._apply_horizontal_aggregation(
                aggregate_report, loop_list, horizontal_aggregator
            )
            aggregate_report = {"hor_ver_agg": [vertical_aggregator(horizontally_aggregated)]}
        else:
            vertically_aggregated = self._apply_vertical_aggregation(aggregate_report, vertical_aggregator)
            ver_hor_aggregated = []
            for elements in zip(*vertically_aggregated.values()):
                ver_hor_aggregated.append(horizontal_aggregator(list(elements)))
            aggregate_report = {"ver_hor_agg": ver_hor_aggregated}
        return aggregate_report

    def _extract_and_check_aggregation_keys(self, filter_content: Dict[str, Any]) -> tuple[str | None, str | None]:
        """
        Extracts horizontal and vertical aggregation keys from the filter content and validates them against
        supported aggregation types.

        Parameters
        ----------
        filter_content : Dict[str, Any]
            A dictionary containing filter criteria, aggregation instructions, and scalar operation details.
            It should include keys for 'horizontal_aggregation' and 'vertical_aggregation' if applicable.

        Returns
        -------
        tuple[str | None, str | None]
            A tuple containing the horizontal and vertical aggregation keys, respectively.
            Returns None for each key if it is not specified or if it is not among the supported types.

        Raises
        ------
        ValueError
            Raised if the specified horizontal or vertical aggregation type is not supported.
            Supported types are defined in the AGGREGATION_FUNCTIONS dictionary.
        """

        horizontal_agg_key = filter_content.get("horizontal_aggregation")
        if horizontal_agg_key and horizontal_agg_key not in AGGREGATION_FUNCTIONS:
            raise ValueError(f"Unsupported horizontal aggregation type: {horizontal_agg_key}")

        vertical_agg_key = filter_content.get("vertical_aggregation")
        if vertical_agg_key and vertical_agg_key not in AGGREGATION_FUNCTIONS:
            raise ValueError(f"Unsupported vertical aggregation type: {vertical_agg_key}")

        return horizontal_agg_key, vertical_agg_key

    def _apply_horizontal_aggregation(
        self,
        report_data: Dict[str, List[float]],
        loop_list: List[str],
        aggregator: Callable[[List[float]], float],
    ) -> List[float]:
        """
        Performs horizontal aggregation on report data using a specified aggregator function.

        Parameters
        ----------
        report_data : Dict[str, List[float]]
            The data pool to be aggregated, structured as a dictionary of lists.
        loop_list : List[str]
            List of keys indicating the order in which to aggregate data.
        aggregator : Callable[[List[float], float, str], float]
            The aggregation function to be used.

        Returns
        -------
        List[float]
            The horizontally aggregated data as a list.

        Raises
        ------
        ValueError
            If the data to be aggregated has different lengths.
        """

        lengths = [len(report_data[key]) for key in loop_list]
        if len(set(lengths)) != 1:
            raise ValueError("Can't aggregate data with different lengths")
        max_length = max(lengths)
        aggregated_data: List[float] = []
        for i in range(max_length):
            temp_data = [report_data[key][i] for key in loop_list]
            non_null_data_points = list(filter(lambda x: x is not None, temp_data))
            aggregated_data.append(aggregator(non_null_data_points))
        return aggregated_data

    def _apply_vertical_aggregation(
        self,
        report_data: Dict[str, List[float]],
        aggregator: Callable[[List[float]], float],
    ) -> Dict[str, List[float]]:
        """
        Performs vertical aggregation on report data using a specified aggregator function.

        Parameters
        ----------
        report_data : Dict[str, List[float]]
            The data pool to be aggregated, structured as a dictionary of lists.
        aggregator : Callable[[List[float], float, str], float]
            The aggregation function to be used.

        Returns
        -------
        Dict[str, List[float]]
            The vertically aggregated data as a dictionary of lists.
        """

        aggregate_data_dict: Dict[str, List[float]] = {}
        for key, data in report_data.items():
            non_null_data_points = list(filter(lambda x: x is not None, data))
            aggregate_data_dict[key] = [aggregator(non_null_data_points)]
        return aggregate_data_dict

    def _add_constants_to_report_data(self, report_data: Dict[str, List[Any]], filter_content: Dict[str, Any]) -> None:
        """
        Add constants to the report data.

        Examples
        --------
        An example of a configuration for constants:
            "constants": {
                "Kilograms to Pounds": 2.20462,
                "Pounds to Dollars": 10
            }

        Parameters
        ----------
        report_data : Dict[str, List[Any]]
            The data to which constants need to be added.
        filter_content : Dict[str, Any]
            A dictionary containing filter criteria, aggregation instructions, and scalar operation details.

        Raises
        ------
        ValueError
            If the name or value of any constant is not valid.
        """

        constants_config = filter_content.get("constants")
        if not constants_config:
            return

        try:
            self._validate_constants(report_data, constants_config)
        except ValueError:
            raise

        max_length = max([len(lst) for lst in report_data.values()])
        for name, value in constants_config.items():
            report_data[name] = [value] * max_length

    def _validate_constants(
        self,
        existing_reports: Dict[str, List[Any]],
        constants_config: Dict[str, int | float],
    ) -> None:
        """
        Validates the names and values of the constants in the constants_config.

        This method checks that each constant's name is not None, a non-empty string, and
        is unique compared to the names of all the existing reports. It also verifies that
        each constant's value is a number (int or float) and not None.

        Parameters
        ----------
        existing_reports : Dict[str, List[Any]]
            The dictionary containing the names and values of the reports that have already been generated.
        constants_config : Dict[str, int | float]
            A dictionary containing the names and values of the constants to be added to the report data.

        Raises
        ------
        ValueError
            If a constant name already exists in the report data.
            If a constant name or value is None.
            If a constant name is not a string.
            If a constant name is empty.
            If a constant value is not a number.
        """

        for name, value in constants_config.items():
            if name in existing_reports:
                raise ValueError(f"Constant name {name} already exists in report data.")

            if name is None:
                raise ValueError("Constant name cannot be None.")

            if value is None:
                raise ValueError("Constant value cannot be None.")

            if not isinstance(name, str):
                raise ValueError(f"Constant name {name} must be a string.")

            if len(name) == 0:
                raise ValueError("Constant name cannot be empty.")

            if not isinstance(value, (int, float)):
                raise ValueError(f"Constant value {value} must be a number.")
