from typing import Dict, List, Any, Callable

from RUFAS.util import Utility


def average_aggregator(data: List[float]) -> float:
    """
    Calculates the average of a list of numbers.

    Parameters
    ----------
    data : List[float]
        A list of numbers whose average is to be calculated.

    Returns
    -------
    float
        The average of the input numbers.
    """
    return sum(data) / len(data) if data else 0


def division_aggregator(data: List[float]) -> float:
    """
    Divides the first number in the list by each of the subsequent numbers.

    Parameters
    ----------
    data : List[float]
        A list of numbers for the division operation.

    Returns
    -------
    float
        The result of dividing the first number by each subsequent number.
        Returns None if the list is empty or has only one element.
    """
    if len(data) < 2:
        return None
    result = data[0]
    for num in data[1:]:
        if num == 0:  # Avoid division by zero
            return None
        result /= num
    return result


def product_aggregator(data: List[float]) -> float:
    """
    Returns the product of a list of numbers.

    Parameters
    ----------
    data : List[float]
        A list of numbers whose product is to be calculated.

    Returns
    -------
    float
        The product of the input numbers. Returns 1 for an empty list.
    """
    product = 1
    for num in data:
        product *= num
    return product


def sd_aggregator(data: List[float]) -> float:
    """
    Calculates the standard deviation of a list of numbers.

    Parameters
    ----------
    data : List[float]
        A list of numbers whose standard deviation is to be calculated.

    Returns
    -------
    float
        The standard deviation of the input numbers.
    """
    mean = average_aggregator(data)
    return (sum((x - mean) ** 2 for x in data) / len(data)) ** 0.5 if data else 0


def sum_aggregator(data: List[float]) -> float:
    """
    Returns the sum of a list of numbers.

    Parameters
    ----------
    data : List[float]
        A list of numbers whose sum is to be calculated.

    Returns
    -------
    float
        The sum of the input numbers.
    """
    return sum(data)


def subtraction_aggregator(data: List[float]) -> float:
    """
    Subtracts each subsequent number in the list from the first number.

    Parameters
    ----------
    data : List[float]
        A list of numbers for the subtraction operation.

    Returns
    -------
    float
        The result of subtracting each subsequent number from the first number.
        Returns None if the list is empty or has only one element.
    """
    if len(data) < 2:
        return None
    result = data[0]
    for num in data[1:]:
        result -= num
    return result


AGGREGATION_FUNCTIONS: Dict[str, Callable[[List[float]], float]] = {
    "average": average_aggregator,
    "division": division_aggregator,
    "product": product_aggregator,
    "SD": sd_aggregator,
    "sum": sum_aggregator,
    "subtraction": subtraction_aggregator,
}


class ReportGenerator:
    """
    A class to generate reports based on filtered data and aggregation criteria and store them in a dictionary.
    """

    def __init__(self):
        """
        Initializes the ReportGenerator.
        """

        self.reports: Dict[str, Dict[str, List[Any]]] = {}

    def clear_reports(self) -> None:
        """
        Clears the reports generated by the ReportGenerator.

        Returns
        -------
        None
        """

        self.reports: Dict[str, Dict[str, List[Any]]] = {}

    def generate_report(
            self,
            filter_content: Dict[str, Any],
            filtered_pool: Dict[str, Dict[str, List[Any]]],
    ) -> List[Dict[str, str | Dict[str, str]]]:
        """
        Generates a single report based on filtered data and aggregation criteria.

        Parameters
        ----------
        filter_content : Dict[str, Any]
            A dictionary containing the configuration for the report, including details
            such as 'name', 'filters', 'cross_references', and aggregation instructions.

        filtered_pool : Dict[str, Dict[str, List[Any]]]
            The data pool from which reports are generated.

        Returns
        -------
        List[Dict[str, str | Dict[str, str]]]
            A list of log events.
        """

        event_logs: List[Dict[str, str | Dict[str, str]]] = []
        info_map = {
            "class": self.__class__.__name__,
            "function": self.generate_report.__name__,
        }

        report_name = self._ensure_unique_report_name_with_timestamp(filter_content.get("name"))

        init_event_log = {
            "log": "start_generate_report",
            "message": f"Start generating report: {report_name}",
            "info_map": info_map,
        }
        event_logs.append(init_event_log)
        data_shallow_copy = dict(filtered_pool)

        try:
            if "cross_references" in filter_content.keys():
                self._check_for_missing_references(filter_content["cross_references"])
                cross_reference_data = {ref: self.reports[ref] for ref in filter_content["cross_references"]}
                data_shallow_copy.update(cross_reference_data)

            report_data = self._generate_report_data(data_shallow_copy, filter_content)

            for col, values in report_data.items():
                column_name = self._ensure_unique_report_name_with_timestamp(f"{report_name}_{col}"
                                                                             if len(report_name) > 0 else col)
                self.reports[column_name] = {"values": values}

        except (KeyError, ValueError) as e:
            error_type = e.__class__.__name__
            error_event_log = {
                "error": "report_generation_error",
                "message": f"Error generating report ({report_name}) => {error_type}: {e}",
                "info_map": info_map,
            }
            event_logs.append(error_event_log)

        return event_logs

    def _ensure_unique_report_name_with_timestamp(self, report_name: str | None) -> str:
        """
        Make the given report name unique, if it is not, by appending a timestamp to it.

        Notes
        -----
        The rules for generating the name are as follows:
        1. If the report name is None, the name is set to `untitled_<timestamp>`.
        2. If the name is not a string, it is converted to a string.
        3. If the name is already present in the list of previously generated reports, the timestamp is appended
            to the name to make it unique.
        4. Otherwise, return the report name as is.

        Parameters
        ----------
        report_name : str | None
            The name of the report.

        Returns
        -------
        str
            The unique name for the report.
        """

        if report_name is None:
            report_name = f"untitled_{Utility.get_timestamp(True)}"

        if report_name in self.reports:
            report_name = f"{report_name}_{Utility.get_timestamp(True)}"

        return report_name

    def _check_for_missing_references(self, references: List[str]) -> None:
        """
        Checks if all the referenced reports are present in the list of previously generated reports.

        Parameters
        ----------
        references : List[str]
            The list of report references to check.

        Raises
        ------
        KeyError
            If any of the report references are missing.
        """

        missing_references = [ref for ref in references if ref not in self.reports]
        if missing_references:
            raise KeyError(f"Missing referenced reports: {', '.join(missing_references)}")

    def _generate_report_data(
            self,
            filtered_pool: Dict[str, Dict[str, List[Any]]],
            filter_content: Dict[str, Any]
    ) -> Dict[str, List[Any]]:
        """
        Generates a report based on filtered data and aggregation criteria, including scalar operations and constants.

        Parameters
        ----------
        filtered_pool : Dict[str, Dict[str, List[Any]]]
            The data pool from which the report is to be generated, structured as a dictionary.
        filter_content : Dict[str, Any]
            A dictionary containing filter criteria, aggregation instructions, and scalar operation details.

        Returns
        -------
        Dict[str, List[Any]]
            If no aggregation is specified, all the columns will be returned.
            If both horizontal and vertical aggregations are specified, the returned dictionary will have one key
                that is either "hor_ver_agg" or "ver_hor_agg" depending on the value of the "horizontal_first" key
                in the filter content.
            If only horizontal aggregation is specified, the returned dictionary will have one key "hor_agg".
            If only vertical aggregation is specified, the returned dictionary will have one key "ver_agg".

        Raises
        ------
        ValueError
            If there is an error preparing the report data.
            If the report data is empty.
            If the type of horizontal or vertical aggregation is not supported.
        """

        try:
            horizontal_agg_key, vertical_agg_key = self._extract_and_check_aggregation_keys(filter_content)
            report_data = self._prepare_report_data_with_constants(filtered_pool, filter_content)
        except ValueError:
            raise

        if not report_data:
            raise ValueError(
                f"filter {filter_content.get('filters')} in {filter_content.get('name')} led to empty report data."
            )

        if not horizontal_agg_key and not vertical_agg_key:
            return report_data

        horizontally_aggregated = None
        vertically_aggregated = None

        if horizontal_agg_key:
            horizontal_aggregator = AGGREGATION_FUNCTIONS.get(horizontal_agg_key)
            loop_list = filter_content.get("horizontal_order", report_data.keys())
            horizontally_aggregated = self._apply_horizontal_aggregation(report_data, loop_list,
                                                                         horizontal_aggregator)

        if vertical_agg_key:
            vertical_aggregator = AGGREGATION_FUNCTIONS.get(vertical_agg_key)
            vertically_aggregated = self._apply_vertical_aggregation(report_data, vertical_aggregator)

        aggregate_report = self._combine_aggregate_report_data(horizontally_aggregated,
                                                               vertically_aggregated,
                                                               filter_content)

        return aggregate_report

    def _combine_aggregate_report_data(
            self,
            horizontally_aggregated: List[float] | None,
            vertically_aggregated: List[float] | None,
            filter_content: Dict[str, Any]
    ) -> Dict[str, List[float]] | None:
        """
        Combines horizontally and vertically aggregated data based on specified aggregation criteria
        from filter_content.

        Parameters
        ----------
        horizontally_aggregated : List[float] | None
            The horizontally aggregated data.
        vertically_aggregated : List[float] | None
            The vertically aggregated data.
        filter_content : Dict[str, Any]
            A dictionary containing filter criteria, aggregation instructions, and scalar operation details.

        Returns
        -------
        Dict[str, List[float]] | None
            If no aggregation is specified, returns None.
            If both horizontal and vertical aggregations are specified, the returned dictionary will have one key
                that is either "hor_ver_agg" or "ver_hor_agg" depending on the value of the "horizontal_first" key
                in the filter content.
            If only horizontal aggregation is specified, the returned dictionary will have one key "hor_agg".
            If only vertical aggregation is specified, the returned dictionary will have one key "ver_agg".
        """

        horizontal_agg_key = filter_content.get("horizontal_aggregation")
        vertical_agg_key = filter_content.get("vertical_aggregation")

        if horizontal_agg_key and vertical_agg_key:
            horizontal_first = filter_content.get("horizontal_first", True)
            aggregator = AGGREGATION_FUNCTIONS[vertical_agg_key if horizontal_first else horizontal_agg_key]
            aggregated_data = horizontally_aggregated if horizontal_first else vertically_aggregated
            return {f"{'hor_ver' if horizontal_first else 'ver_hor'}_agg": [aggregator(aggregated_data)]}

        if horizontal_agg_key:
            return {"hor_agg": horizontally_aggregated}

        if vertical_agg_key:
            return {"ver_agg": vertically_aggregated}

        return None

    def _extract_and_check_aggregation_keys(
            self,
            filter_content: Dict[str, Any]
    ) -> tuple[str | None, str | None]:
        """
        Extracts horizontal and vertical aggregation keys from the filter content and validates them against
        supported aggregation types.

        Parameters
        ----------
        filter_content : Dict[str, Any]
            A dictionary containing filter criteria, aggregation instructions, and scalar operation details.
            It should include keys for 'horizontal_aggregation' and 'vertical_aggregation' if applicable.

        Returns
        -------
        tuple[str | None, str | None]
            A tuple containing the horizontal and vertical aggregation keys, respectively.
            Returns None for each key if it is not specified or if it is not among the supported types.

        Raises
        ------
        ValueError
            Raised if the specified horizontal or vertical aggregation type is not supported.
            Supported types are defined in the AGGREGATION_FUNCTIONS dictionary.
        """

        horizontal_agg_key = filter_content.get("horizontal_aggregation")
        if horizontal_agg_key and horizontal_agg_key not in AGGREGATION_FUNCTIONS:
            raise ValueError(f"Unsupported horizontal aggregation type: {horizontal_agg_key}")

        vertical_agg_key = filter_content.get("vertical_aggregation")
        if vertical_agg_key and vertical_agg_key not in AGGREGATION_FUNCTIONS:
            raise ValueError(f"Unsupported vertical aggregation type: {vertical_agg_key}")

        return horizontal_agg_key, vertical_agg_key

    def _apply_horizontal_aggregation(
            self,
            report_data: Dict[str, List[float]], loop_list: List[str],
            aggregator: Callable[[List[float]], float]) -> List[float]:
        """
        Performs horizontal aggregation on report data using a specified aggregator function.

        Parameters
        ----------
        report_data : Dict[str, List[float]]
            The data pool to be aggregated, structured as a dictionary of lists.
        loop_list : List[str]
            List of keys indicating the order in which to aggregate data.
        aggregator : Callable[[List[float], float, str], float]
            The aggregation function to be used.

        Returns
        -------
        List[float]
            The horizontally aggregated data as a list.

        Raises
        ------
        ValueError
            If the data to be aggregated has different lengths.
        """

        lengths = [len(report_data[key]) for key in loop_list]
        if len(set(lengths)) != 1:
            raise ValueError("Can't aggregate data with different lengths")
        max_length = max(lengths)
        aggregated_data: List[float] = []
        for i in range(max_length):
            temp_data = [report_data[key][i] for key in loop_list]
            non_null_data_points = list(filter(None.__ne__, temp_data))
            aggregated_data.append(aggregator(non_null_data_points))
        return aggregated_data

    def _apply_vertical_aggregation(
            self,
            report_data: Dict[str, List[float]],
            aggregator: Callable[[List[float]], float]) -> List[float]:
        """
        Performs vertical aggregation on report data using a specified aggregator function.

        Parameters
        ----------
        report_data : Dict[str, List[float]]
            The data pool to be aggregated, structured as a dictionary of lists.
        aggregator : Callable[[List[float], float, str], float]
            The aggregation function to be used.

        Returns
        -------
        List[float]
            The vertically aggregated data as a list.
        """

        aggregated_data: List[float] = []
        for _, data in report_data.items():
            non_null_data_points = list(filter(None.__ne__, data))
            aggregated_data.append(aggregator(non_null_data_points))
        return aggregated_data

    def _prepare_report_data_with_constants(
            self,
            filtered_pool: Dict[str, Dict[str, List[Any]]],
            filter_content: Dict[str, Any]) -> Dict[str, List[Any]]:
        """
        Processes and structures a filtered data pool for report generation.

        Notes
        -----
        This method organizes data from a filtered pool based on selected variables and slicing parameters.
        It caters to different data structures within the pool, ensuring data is formatted appropriately
        for report inclusion.

        Parameters
        ----------
        filtered_pool : Dict[str, pool_element_type]
            The filtered data pool with each key mapping to its respective data element.

        filter_content : Dict[str, Any]
            A dictionary containing filter criteria, aggregation instructions, and scalar operation details.

        Returns
        -------
        Dict[str, List[Any]]
            Processed data suitable for report generation, keyed by selected variables.

        Raises
        ------
        KeyError
            If selected_variables is None and the data within the pool requires variable selection.
        ValueError
            If the name or value of any constant is not valid.
        """

        selected_variables = filter_content.get("variables")
        slice_start = filter_content.get("slice_start", 0)
        slice_end = filter_content.get("slice_end")
        report_data: Dict[str, List[Any]] = {}

        for key in filtered_pool.keys():
            is_data_in_dict = isinstance(filtered_pool[key]["values"][0], dict)
            if is_data_in_dict and selected_variables is None:
                raise KeyError(
                    "Can't generate report, use 'variables' arg to select items from data"
                )
            if is_data_in_dict:
                temp_data = Utility.convert_list_of_dicts_to_dict_of_lists(
                    filtered_pool[key]["values"][slice_start:slice_end]
                )
                for temp_key, temp_values in temp_data.items():
                    if temp_key not in selected_variables:
                        continue
                    if temp_key in report_data:
                        report_data[temp_key].extend(temp_values)
                    else:
                        report_data[temp_key] = temp_values
            else:
                report_data[key] = filtered_pool[key]["values"][slice_start:slice_end]

        try:
            self._add_constants_to_report_data(report_data, filter_content)
        except ValueError:
            raise

        return report_data

    def _add_constants_to_report_data(
            self,
            report_data: Dict[str, List[Any]],
            filter_content: Dict[str, Any]) -> None:
        """
        Add constants to the report data.

        Examples
        --------
        An example of a configuration for constants:
            "constants": {
                "Kilograms to Pounds": 2.20462,
                "Pounds to Dollars": 10
            }

        Parameters
        ----------
        report_data : Dict[str, List[Any]]
            The data to which constants need to be added.
        filter_content : Dict[str, Any]
            A dictionary containing filter criteria, aggregation instructions, and scalar operation details.

        Raises
        ------
        ValueError
            If the name or value of any constant is not valid.
        """

        constants_config = filter_content.get("constants")
        if not constants_config:
            return

        try:
            self._validate_constants(report_data, constants_config)
        except ValueError:
            raise

        max_length = max([len(lst) for lst in report_data.values()])
        for name, value in constants_config.items():
            report_data[name] = [value] * max_length

    def _validate_constants(
            self,
            report_data: Dict[str, List[Any]],
            constant_config: Dict[str, int | float]
    ) -> None:
        """
        Validate constants before adding them to report data.

        Parameters
        ----------
        report_data : Dict[str, List[Any]]
            The existing report data.
        constant_config : Dict[str, int | float]
            The configuration of constants to be added.

        Raises
        ------
        ValueError
            If a constant name already exists in the report data.
            If a constant name or value is None.
            If a constant name is not a string.
            If a constant name is empty.
            If a constant value is not a number.
        """

        for name, value in constant_config.items():
            if name in report_data:
                raise ValueError(f"Constant name {name} already exists in report data.")

            if name is None:
                raise ValueError("Constant name cannot be None.")

            if value is None:
                raise ValueError("Constant value cannot be None.")

            if not isinstance(name, str):
                raise ValueError(f"Constant name {name} must be a string.")

            if len(name) == 0:
                raise ValueError("Constant name cannot be empty.")

            if not isinstance(value, (int, float)):
                raise ValueError(f"Constant value {value} must be a number.")
