from __future__ import annotations

from typing import Dict, List, Any, Callable

from RUFAS.util import Utility


def average_aggregator(data: List[float]) -> float:
    """
    Calculates the average of a list of numbers.

    Parameters
    ----------
    data : List[float]
        A list of numbers whose average is to be calculated.

    Returns
    -------
    float
        The average of the input numbers.
    """
    return sum(data) / len(data) if data else 0


def division_aggregator(data: List[float]) -> float:
    """
    Divides the first number in the list by each of the subsequent numbers.

    Parameters
    ----------
    data : List[float]
        A list of numbers for the division operation.

    Returns
    -------
    float
        The result of dividing the first number by each subsequent number.
        Returns None if the list is empty or has only one element.
    """
    if len(data) < 2:
        return None
    result = data[0]
    for num in data[1:]:
        if num == 0:  # Avoid division by zero
            return None
        result /= num
    return result


def product_aggregator(data: List[float]) -> float:
    """
    Returns the product of a list of numbers.

    Parameters
    ----------
    data : List[float]
        A list of numbers whose product is to be calculated.

    Returns
    -------
    float
        The product of the input numbers. Returns 1 for an empty list.
    """
    product = 1
    for num in data:
        product *= num
    return product


def sd_aggregator(data: List[float]) -> float:
    """
    Calculates the standard deviation of a list of numbers.

    Parameters
    ----------
    data : List[float]
        A list of numbers whose standard deviation is to be calculated.

    Returns
    -------
    float
        The standard deviation of the input numbers.
    """
    mean = average_aggregator(data)
    return (sum((x - mean) ** 2 for x in data) / len(data)) ** 0.5 if data else 0


def sum_aggregator(data: List[float]) -> float:
    """
    Returns the sum of a list of numbers.

    Parameters
    ----------
    data : List[float]
        A list of numbers whose sum is to be calculated.

    Returns
    -------
    float
        The sum of the input numbers.
    """
    return sum(data)


def subtraction_aggregator(data: List[float]) -> float:
    """
    Subtracts each subsequent number in the list from the first number.

    Parameters
    ----------
    data : List[float]
        A list of numbers for the subtraction operation.

    Returns
    -------
    float
        The result of subtracting each subsequent number from the first number.
        Returns None if the list is empty or has only one element.
    """
    if len(data) < 2:
        return None
    result = data[0]
    for num in data[1:]:
        result -= num
    return result


AGGREGATION_FUNCTIONS: Dict[str, Callable[[List[float]], float]] = {
    "average": average_aggregator,
    "division": division_aggregator,
    "product": product_aggregator,
    "SD": sd_aggregator,
    "sum": sum_aggregator,
    "subtraction": subtraction_aggregator,
}


class ReportGenerator:
    """
    A class to generate reports based on filtered data and aggregation criteria and store them in a dictionary.
    """

    def __init__(self):
        """
        Initializes the ReportGenerator.
        """

        self.reports: Dict[str, Dict[str, List[Any]]] = {}

    def clear_reports(self) -> None:
        """
        Clears the reports generated by the ReportGenerator.

        Returns
        -------
        None
        """

        self.reports = {}

    def generate_report(
            self,
            filtered_pool: Dict[str, Dict[str, List[Any]]],
            filter_content: Dict[str, str | int | List[str]],
    ) -> Dict[str, List[float]]:
        """
        Generates a report based on filtered data and aggregation criteria.

        This method processes filtered data and performs specified horizontal and/or vertical aggregations
        based on the instructions provided in filter_content.

        Parameters
        ----------
        filtered_pool : Dict[str, Dict[str, List[Any]]]
            The data pool from which the report is to be generated, structured as a dictionary.
            Has the same structure of OutputManager's variables pool.

        filter_content : Dict[str, str | int | List[str]]
            A dictionary containing filter criteria and aggregation instructions.

        Returns
        -------
        Dict[str, List[float]]
            The sliced and aggregated data.

        Raises
        ------
        ValueError
            If the report data is empty or if the necessary aggregation keys are not found in filter_content.
        KeyError
            If a key specified in the `horizontal_order` of `filter_content` is not found in the `report_data`.
            This usually indicates a mismatch between the expected structure of `filtered_pool` and its actual content.
        """
        report_data = self._prepare_report_data(
            filtered_pool,
            selected_variables=filter_content.get("variables"),
            slice_start=filter_content.get("slice_start", 0),
            slice_end=filter_content.get("slice_end"),
        )
        if not report_data:
            raise ValueError(
                f"filter {filter_content.get('filters')} in {filter_content.get('name')} led to empty report data."
            )

        horizontal_agg_key = filter_content.get("horizontal_aggregation")
        horizontal_aggregator = AGGREGATION_FUNCTIONS.get(horizontal_agg_key)

        vertical_agg_key = filter_content.get("vertical_aggregation")
        vertical_aggregator = AGGREGATION_FUNCTIONS.get(vertical_agg_key)

        if horizontal_aggregator:
            loop_list = filter_content.get("horizontal_order", report_data.keys())
            number_of_elements = len(report_data[next(iter(report_data))])
            try:
                horizontally_aggregated = [
                    horizontal_aggregator([report_data[key][i] for key in loop_list])
                    for i in range(number_of_elements)
                ]
            except KeyError as e:
                raise KeyError(
                    f"{e.args[0]} not found in filtered pool. Check the `horizontal_order` entry in the filter file."
                )
            if not vertical_aggregator:
                return {"hor_agg": horizontally_aggregated}

        if vertical_aggregator:
            vertically_aggregated = [
                vertical_aggregator(data_series)
                for _, data_series in report_data.items()
            ]
            if not horizontal_aggregator:
                return {"ver_agg": vertically_aggregated}

            if filter_content.get("horizontal_first", False):
                return {"hor_ver_agg": [vertical_aggregator(horizontally_aggregated)]}
            return {"ver_hor_agg": [horizontal_aggregator(vertically_aggregated)]}

        return report_data

    def _prepare_report_data(
            self,
            filtered_pool: Dict[str, Dict[str, List[Any]]],
            selected_variables: List[str],
            slice_start: int,
            slice_end: int,
    ) -> Dict[str, List[Any]]:
        """
        Processes and structures a filtered data pool for report generation.

        This method organizes data from a filtered pool based on selected variables and slicing parameters.
        It caters to different data structures within the pool, ensuring data is formatted appropriately
        for report inclusion.

        Parameters
        ----------
        filtered_pool : Dict[str, pool_element_type]
            The filtered data pool with each key mapping to its respective data element.

        selected_variables : List[str]
            Variables to be included from the filtered pool.

        slice_start : int
            Starting index for slicing data elements.

        slice_end : int
            Ending index for slicing.

        Returns
        -------
        Dict[str, List[Any]]
            Processed data suitable for report generation, keyed by selected variables.

        Raises
        ------
        KeyError
            If selected_variables is None and the data within the pool requires variable selection.
        """
        report_data: Dict[str, List[Any]] = {}
        for key in filtered_pool.keys():
            is_data_in_dict = isinstance(filtered_pool[key]["values"][0], dict)
            if is_data_in_dict and selected_variables is None:
                raise KeyError(
                    "Can't generate report, use 'variables' arg to select items from data"
                )
            if is_data_in_dict:
                temp_data = Utility.convert_list_of_dicts_to_dict_of_lists(
                    filtered_pool[key]["values"][slice_start:slice_end]
                )
                for temp_key, temp_values in temp_data.items():
                    if temp_key not in selected_variables:
                        continue
                    if temp_key in report_data:
                        report_data[temp_key].extend(temp_values)
                    else:
                        report_data[temp_key] = temp_values
            else:
                report_data[key] = filtered_pool[key]["values"][slice_start:slice_end]
        return report_data

    def handle_report_generation(
            self,
            filter_content: Dict[str, Any],
            filtered_pool: Dict[str, Dict[str, List[Any]]],
    ) -> List[Dict[str, str | Dict[str, str]]]:
        """
        Generates a single report based on filtered data and aggregation criteria.

        Parameters
        ----------
        filter_content : Dict[str, Any]
            A dictionary containing the configuration for the report, including details
            such as 'name', 'filters', 'cross_references', and aggregation instructions.

        filtered_pool : Dict[str, Dict[str, List[Any]]]
            The data pool from which reports are generated.

        Returns
        -------
        List[Dict[str, str | Dict[str, str]]]
            A list of log events.
        """

        event_logs: List[Dict[str, str | Dict[str, str]]] = []
        info_map = {
            "class": self.__class__.__name__,
            "function": self.handle_report_generation.__name__,
        }

        report_name = self._generate_unique_report_name(filter_content.get("name"))

        init_event = {
            "log": "start_generate_report",
            "message": f"Start generating report: {report_name}",
            "info_map": info_map,
        }
        event_logs.append(init_event)
        data = dict(filtered_pool)

        try:
            if "cross_references" in filter_content.keys():
                self._check_for_missing_references(filter_content["cross_references"])
                cross_reference_data = {ref: self.reports[ref] for ref in filter_content["cross_references"]}
                data.update(cross_reference_data)

            report_data = self._generate_single_report(data, filter_content)

            for col, values in report_data.items():
                column_name = self._generate_unique_report_name(f"{report_name}_{col}")
                self.reports[column_name] = {"values": values}

        except (KeyError, ValueError) as e:
            error_type = e.__class__.__name__
            error_event = {
                "error": "report_generation_error",
                "message": f"Error generating report ({report_name}) => {error_type}: {e}",
                "info_map": info_map,
            }
            event_logs.append(error_event)

        return event_logs

    def _generate_unique_report_name(self, report_name: str | None) -> str:
        """
        Make the given report name unique, if it is not, by appending a timestamp to it.

        Notes
        -----
        The rules for generating the name are as follows:
        1. If the report name is None or empty, the name is set to `untitled_<timestamp>`.
        2. If the name is already present in the list of previously generated reports, the timestamp is appended
            to the name to make it unique.
        3. Otherwise, return the report name as is.

        Parameters
        ----------
        report_name : str | None
            The name of the report.

        Returns
        -------
        str
            The unique name for the report.
        """

        if not report_name or not isinstance(report_name, str) or len(report_name) == 0:
            return f"untitled_{Utility.get_timestamp(True)}"

        if report_name in self.reports:
            report_name = f"{report_name} {Utility.get_timestamp(True)}"

        return report_name

    def _check_for_missing_references(self, references: List[str]) -> None:
        """
        Checks if all the referenced reports are present.

        Parameters
        ----------
        references : List[str]
            The list of report references to check.

        Raises
        ------
        KeyError
            If any of the report references are missing.
        """

        missing_references = [ref for ref in references if ref not in self.reports]
        if missing_references:
            raise KeyError(f"Missing referenced reports: {', '.join(missing_references)}")

    @staticmethod
    def _generate_single_report(
            filtered_pool: Dict[str, Dict[str, List[Any]]],
            filter_content: Dict[str, Any]
    ) -> Dict[str, List[Any]]:
        """
        Generates a report based on filtered data and aggregation criteria, including scalar operations and constants.

        Parameters
        ----------
        filtered_pool : Dict[str, Dict[str, List[Any]]]
            The data pool from which the report is to be generated, structured as a dictionary.
        filter_content : Dict[str, Any]
            A dictionary containing filter criteria, aggregation instructions, and scalar operation details.

        Returns
        -------
        Dict[str, List[Any]]
            If no aggregation is specified, all the columns will be returned.
            If both horizontal and vertical aggregations are specified, the returned dictionary will have one key
                that is either "hor_ver_agg" or "ver_hor_agg" depending on the value of the "horizontal_first" key
                in the filter content.
            If only horizontal aggregation is specified, the returned dictionary will have one key "hor_agg".
            If only vertical aggregation is specified, the returned dictionary will have one key "ver_agg".

        Raises
        ------
        ValueError
            If there is an error preparing the report data.
            If the report data is empty.
            If the type of horizontal or vertical aggregation is not supported.
        """

        try:
            report_data = ReportGenerator._prepare_report_data_with_constants(filtered_pool, filter_content)
        except ValueError as e:
            raise ValueError(f"Error preparing report data => {e}")

        if not report_data:
            raise ValueError(
                f"filter {filter_content.get('filters')} in {filter_content.get('name')} led to empty report data."
            )

        try:
            horizontal_agg_key, vertical_agg_key = ReportGenerator._validate_aggregation_keys(filter_content)
        except ValueError as e:
            raise ValueError(f"Error validating aggregation keys => {e}")

        horizontally_aggregated = None
        vertically_aggregated = None
        horizontal_aggregator = None
        vertical_aggregator = None

        if horizontal_agg_key:
            horizontal_aggregator = AGGREGATION_FUNCTIONS.get(horizontal_agg_key)
            loop_list = filter_content.get("horizontal_order", report_data.keys())
            horizontally_aggregated = ReportGenerator._apply_horizontal_aggregation(report_data, loop_list,
                                                                                    horizontal_aggregator)

        if vertical_agg_key:
            vertical_aggregator = AGGREGATION_FUNCTIONS.get(vertical_agg_key)
            vertically_aggregated = ReportGenerator._apply_vertical_aggregation(report_data, vertical_aggregator)

        if horizontal_agg_key and vertical_agg_key:
            horizontal_first = filter_content.get("horizontal_first", True)
            if horizontal_first:
                return {"hor_ver_agg": [vertical_aggregator(horizontally_aggregated)]}
            return {"ver_hor_agg": [horizontal_aggregator(vertically_aggregated)]}

        if horizontal_agg_key:
            return {"hor_agg": horizontally_aggregated}

        if vertical_agg_key:
            return {"ver_agg": vertically_aggregated}

        return report_data

    @staticmethod
    def _validate_aggregation_keys(filter_content: Dict[str, Any]) -> tuple[str | None, str | None]:
        """
        Validates the horizontal and vertical aggregation keys in the filter content.

        Parameters
        ----------
        filter_content : Dict[str, Any]
            A dictionary containing filter criteria, aggregation instructions, and scalar operation details.

        Returns
        -------
        tuple[str | None, str | None]
            The horizontal and vertical aggregation keys.

        Raises
        ------
        ValueError
            If the type of horizontal or vertical aggregation is not supported. The supported types are:
            sum, average, product, subtraction, division, SD.
        """

        horizontal_agg_key = filter_content.get("horizontal_aggregation")
        if horizontal_agg_key and horizontal_agg_key not in AGGREGATION_FUNCTIONS:
            raise ValueError(f"Unsupported horizontal aggregation type: {horizontal_agg_key}")

        vertical_agg_key = filter_content.get("vertical_aggregation")
        if vertical_agg_key and vertical_agg_key not in AGGREGATION_FUNCTIONS:
            raise ValueError(f"Unsupported vertical aggregation type: {vertical_agg_key}")

        return horizontal_agg_key, vertical_agg_key

    @staticmethod
    def _apply_horizontal_aggregation(report_data: Dict[str, List[float]], loop_list: List[str],
                                      aggregator: Callable[[List[float]], float]) -> List[float]:
        """
        Performs horizontal aggregation on report data using a specified aggregator function.

        Parameters
        ----------
        report_data : Dict[str, List[float]]
            The data pool to be aggregated, structured as a dictionary of lists.
        loop_list : List[str]
            List of keys indicating the order in which to aggregate data.
        aggregator : Callable[[List[float], float, str], float]
            The aggregation function to be used.

        Returns
        -------
        List[float]
            The horizontally aggregated data as a list.

        Raises
        ------
        ValueError
            If the data to be aggregated has different lengths.
        """

        lengths = [len(report_data[key]) for key in loop_list]
        if len(set(lengths)) != 1:
            raise ValueError("Can't aggregate data with different lengths")
        max_length = max(lengths)
        aggregated_data = []
        for i in range(max_length):
            temp_data = [report_data[key][i] for key in loop_list]
            filtered_temp_data = list(filter(None.__ne__, temp_data))
            aggregated_data.append(aggregator(filtered_temp_data))
        return aggregated_data

    @staticmethod
    def _apply_vertical_aggregation(report_data: Dict[str, List[float]],
                                    aggregator: Callable[[List[float]], float]) -> List[float]:
        """
        Performs vertical aggregation on report data using a specified aggregator function.

        Parameters
        ----------
        report_data : Dict[str, List[float]]
            The data pool to be aggregated, structured as a dictionary of lists.
        aggregator : Callable[[List[float], float, str], float]
            The aggregation function to be used.

        Returns
        -------
        List[float]
            The vertically aggregated data as a list.
        """

        aggregated_data = []
        for _, data in report_data.items():
            filtered_data = list(filter(None.__ne__, data))
            aggregated_data.append(aggregator(filtered_data))
        return aggregated_data

    @staticmethod
    def _prepare_report_data_with_constants(filtered_pool: Dict[str, Dict[str, List[Any]]],
                                            filter_content: Dict[str, Any]) -> Dict[str, List[Any]]:
        """
        Processes and structures a filtered data pool for report generation.

        Notes
        -----
        This method organizes data from a filtered pool based on selected variables and slicing parameters.
        It caters to different data structures within the pool, ensuring data is formatted appropriately
        for report inclusion.

        Parameters
        ----------
        filtered_pool : Dict[str, pool_element_type]
            The filtered data pool with each key mapping to its respective data element.

        filter_content : Dict[str, Any]
            A dictionary containing filter criteria, aggregation instructions, and scalar operation details.

        Returns
        -------
        Dict[str, List[Any]]
            Processed data suitable for report generation, keyed by selected variables.

        Raises
        ------
        KeyError
            If selected_variables is None and the data within the pool requires variable selection.
        ValueError
            If the name or value of any constant is not valid.
        """

        selected_variables = filter_content.get("variables")
        slice_start = filter_content.get("slice_start", 0)
        slice_end = filter_content.get("slice_end")
        report_data: Dict[str, List[Any]] = {}

        for key in filtered_pool.keys():
            is_data_in_dict = isinstance(filtered_pool[key]["values"][0], dict)
            if is_data_in_dict and selected_variables is None:
                raise KeyError(
                    "Can't generate report, use 'variables' arg to select items from data"
                )
            if is_data_in_dict:
                temp_data = Utility.convert_list_of_dicts_to_dict_of_lists(
                    filtered_pool[key]["values"][slice_start:slice_end]
                )
                for temp_key, temp_values in temp_data.items():
                    if temp_key not in selected_variables:
                        continue
                    if temp_key in report_data:
                        report_data[temp_key].extend(temp_values)
                    else:
                        report_data[temp_key] = temp_values
            else:
                report_data[key] = filtered_pool[key]["values"][slice_start:slice_end]

        try:
            ReportGenerator._add_constants_data(report_data, filter_content)
        except ValueError as e:
            raise ValueError(f"Error adding constants => {e}")

        return report_data

    @staticmethod
    def _add_constants_data(
            report_data: Dict[str, List[Any]],
            filter_content: Dict[str, Any]) -> None:
        """
        Add constants to the report data.

        Examples
        --------
        An example of a configuration for constants:
            "constants": {
                "Kilograms to Pounds": 2.20462,
                "Pounds to Dollars": 10
            }

        Parameters
        ----------
        report_data : Dict[str, List[Any]]
            The data to which constants need to be added.
        filter_content : Dict[str, Any]
            A dictionary containing filter criteria, aggregation instructions, and scalar operation details.

        Returns
        -------
        None

        Raises
        ------
        ValueError
            If the name or value of any constant is not valid.
        """

        constant_config = filter_content.get("constants")
        if not constant_config:
            return

        try:
            ReportGenerator._validate_constants(report_data, constant_config)
        except ValueError as e:
            raise ValueError(f"Error validating constants => {e}")

        max_length = max([len(lst) for lst in report_data.values()])
        for name, value in constant_config.items():
            report_data[name] = [value] * max_length

    @staticmethod
    def _validate_constants(
            report_data: Dict[str, List[Any]],
            constant_config: Dict[str, int | float]
    ) -> None:
        """
        Validate constants before adding them to report data.

        Parameters
        ----------
        report_data : Dict[str, List[Any]]
            The existing report data.
        constant_config : Dict[str, int | float]
            The configuration of constants to be added.

        Raises
        ------
        ValueError
            If a constant name already exists in the report data.
            If a constant name or value is None.
            If a constant name is not a string.
            If a constant name is empty.
            If a constant value is not a number.
        """

        for name, value in constant_config.items():
            if name in report_data:
                raise ValueError(f"Constant name {name} already exists in report data.")

            if name is None:
                raise ValueError("Constant name cannot be None.")

            if value is None:
                raise ValueError("Constant value cannot be None.")

            if not isinstance(name, str):
                raise ValueError(f"Constant name {name} must be a string.")

            if len(name) == 0:
                raise ValueError("Constant name cannot be empty.")

            if not isinstance(value, (int, float)):
                raise ValueError(f"Constant value {value} must be a number.")
