from enum import Enum, unique


@unique
class MeasurementUnits(Enum):
    """
    A list of acceptable units used within the RuFaS model.

    """

    ANIMALS: str = "animals"
    ARTIFICIAL_INSEMINATIONS: str = "AIs"
    CALENDAR_YEAR: str = "calendar year"
    CONCEPTIONS: str = "conceptions"
    CONCEPTIONS_PER_SERVICE: str = "conceptions per service"
    COWS: str = "cows"
    CUBIC_METERS: str = "m^3"
    CUBIC_METERS_PER_DAY: str = "m^3/day"
    DAYS: str = "days"
    DEGREES_CELSIUS: str = "°C"
    DRY_KILOGRAMS: str = "dry kg"
    DRY_KILOGRAMS_PER_HECTARE: str = "dry kg/ha"
    FRACTION: str = "fraction"
    GRAMS: str = "g"
    GRAMS_PER_DAY: str = "g/day"
    GRAMS_PER_LITER: str = "g/L"
    HECTARE: str = "ha"
    HOURS: str = "hours"
    INJECTIONS: str = "injections"
    KILOGRAMS: str = "kg"
    KILOGRAMS_CARBON_DIOXIDE_PER_KILOGRAM_DRY_MATTER: str = "kg CO2 / kg DM"
    KILOGRAMS_PER_ANIMAL: str = "kg/animal"
    KILOGRAMS_PER_DAY: str = "kg/day"
    KILOGRAMS_PER_HECTARE: str = "kg/ha"
    MEGACALORIES: str = "Mcal"
    MEGACALORIES_PER_KILOGRAM: str = "Mcal/kg"
    MEGAJOULES: str = "MJ"
    MEGAJOULES_PER_CUBIC_METER: str = "MJ/m^3"
    MEGAJOULES_PER_SQUARE_METER: str = "MJ/m^2"
    METERS: str = "m"
    METRIC_TONS: str = "metric tons"
    MILLIMETERS: str = "mm"
    MILLIMETERS_PER_HECTARE: str = "mm/ha"
    ORDINAL_DAY: str = "ordinal day"
    PERCENT: str = "percent"
    PERCENT_OF_DRY_MATTER: str = "percent of DM"
    PREGNANCY_CHECKS: str = "preg checks"
    SIMULATION_DAY: str = "simulation day"
    SIMULATION_YEAR: str = "simulation year"
    UNITLESS: str = "unitless"
    WET_KILOGRAMS_PER_HECTARE: str = "wet kg/ha"
