[mypy]
# Specify the Python version used for type checking.
python_version = 3.10

# Ignore errors for missing type stubs of external libraries.
ignore_missing_imports = True

# Make types for None explicit, requiring optional types to be explicitly annotated.
strict_optional = True

# Disallow defining functions without type annotations.
disallow_untyped_defs = True

# Check the bodies of untyped functions, applying type inference where possible.
check_untyped_defs = True

# Disallow the use of Any as a type unless explicitly declared.
disallow_any_generics = True

# Require all variables to be explicitly typed.
disallow_incomplete_defs = True

# Show column numbers in error messages.
show_column_numbers = True