---
title: Scenario 6
---
flowchart LR
    Start --> Handler["Flush System"]
    Handler --> ReceptionPit["Reception Pit"]
    ReceptionPit --> Separator["Rotary Screen"]
    Separator --> Treatment1["Anaerobic Digestion"]
    Treatment1 --> Treatment2["Anaerobic Lagoon"]
    Treatment2 --> Done[End]