---
title: Scenario 5
---
flowchart LR
    Start --> Handler["Manual Scraping"]
    Handler --> ReceptionPit["Reception Pit"]
    ReceptionPit --> Treatment1["Anaerobic Digestion"]
    Treatment1 --> Treatment2["Aerobic Lagoon"]
    Treatment2 --> Done[End]