---
title: Scenario 2
---
flowchart LR
    Start --> Handler["Manual Scraping"]
    Handler --> ReceptionPit["Reception Pit"]
    ReceptionPit --> Separator["Screw Press"]
    Separator --> Treatment["Slurry Storage Outdoor"]
    Treatment --> Done[End]