---
title: Scenario 1
---
flowchart LR
    Start --> Handler["Manual Scraping"]
    Handler --> ReceptionPit["Reception Pit"]
    ReceptionPit --> Treatment["Slurry Storage Outdoor"]
    Treatment --> Done[End]