---
title: Scenario 3
---
flowchart LR
    Start --> Handler["Flush System"]
    Handler --> ReceptionPit["Reception Pit"]
    ReceptionPit --> Treatment["Anaerobic Lagoon"]
    Treatment --> Done[End]