---
title: Scenario 0
---
flowchart LR
    Start --> Handler["Manual Scraping"]
    Handler --> ReceptionPit["Reception Pit"]
    ReceptionPit --> Treatment["Anaerobic Lagoon"]
    Treatment --> Done[End]