---
title: Scenario 7
---
flowchart LR
    Start --> Handler["Flush System"]
    Handler --> ReceptionPit["Reception Pit"]
    ReceptionPit --> Treatment1["Anaerobic Digestion"]
    Treatment1 --> Separator["Rotary Screen"]
    Separator --> Treatment2["Anaerobic Lagoon"]
    Treatment2 --> Done[End]