---
title: Scenario 8
---
flowchart LR
    Start --> Handler["Compost Bedded Packed Barn Scraping"]
    Handler --> ReceptionPit["Reception Pit"]
    ReceptionPit --> Treatment["Compost Bedded Packed Barn"]
    Treatment --> Done[End]