from .harvested_crop import HarvestedCrop
from .storage import Storage
from .enums import CropCategory, BaleSize
from RUFAS.current_day_conditions import CurrentDayConditions
from RUFAS.time import Time

class Hay(Storage):
    """
    Represents a Hay storage subclass of Storage.

    Attributes
    ----------
    bale_density : float
        Density of the hay bale calculated based on its moisture content.
    bale_size : float
        Diameter of the hay bale in meters.

    Methods
    -------
    calculate_protein_loss():
        Calculates the protein loss in the hay.
    """

    def __init__(self, bale_diameter: BaleSize, capacity: float = float("inf")):
        super().__init__(capacity)
        self.acceptable_crops = [
            CropCategory.ALFALFA,
            CropCategory.GRASS,
            CropCategory.SMALL_GRAIN,
        ]
        self.bale_diameter = bale_diameter
        self.additional_loss_coefficient = None

    @property
    def bale_density(self) -> float:
        """
        Calculate and return the density of the hay bale.

        Returns
        -------
        float
            The density of the hay bale.
        """
        densities = []
        for crop in self.stored:
            moisture_at_baling = 100 - crop.initial_dry_matter_percentage
            bale_density = self.calculate_bale_density(moisture_at_baling)
            densities.append(bale_density)
        average_density = sum(densities) / len(densities)
        return average_density

    @property
    def bale_size(self) -> float:
        """
        Return the size (diameter) of the hay bale.

        Returns
        -------
        float
            The diameter of the hay bale in meters.
        """
        return self.bale_diameter.value()

    def calculate_protein_loss(self):
        """
        Calculates the protein loss in the hay.

        Returns
        -------
        None
        """
        pass

    def calculate_dry_matter_loss_to_gas(
        self, crop: HarvestedCrop, current_conditions: CurrentDayConditions, time: Time
    ) -> float:
        """
        Calculates the amount of gaseous dry matter lost.

        Parameters
        ----------
        crop : HarvestedCrop
            The stored crop that is losing dry matter.
        current_conditions : CurrentDayConditions
            Current conditions of the simulated day.
        time : Time
            Time instance containing the current time of the simulation.

        Returns
        -------
        float
            Amount of gaseous dry matter lost from the crop on the current day in kg.
        
        """
        days_stored = crop.days_stored(time)
        if days_stored <= 30:
            stored_dry_matter = crop.initial_dry_matter_percentage * crop.initial_fresh_mass
            density = self.calculate_bale_density(stored_dry_matter)
            heat = self.calculate_heat_generated(crop.initial_dry_matter_percentage, density)
            moisture_factor = 1.0
            moisture_fraction_at_baling = (100 - crop.initial_dry_matter_percentage) / 100
            cumulative_dry_matter_loss = heat + 2433 * (moisture_at_baling - moisture_factor * (1 - moisture )
                                                        
    def _calculate_cumulative_gaseous_dry_matter_loss(
        self, heat: float, moisture_at_baling: float, days_baled: int
    ) -> float:
        """
        Calculates the cumulative gaseous dry matter loss in hay.

        Parameters
        ----------
        heat : float
            Total sensible heat generated by the hay in kJ per kg.
        moisture_at_baling : float
            Fraction of fresh mass that was not dry matter when hay was baled.
        days_baled : float
            Number of days since crop was baled.

        Returns
        -------
        float
            Total amount of gaseous dry matter loss from the hay since storage in kg.    

        """
        moisture_factor = 1.0
        days_baled_adjuster = 0.004 * days_baled
        dry_matter_at_baling = 1 - moisture_at_baling
        numerator = 2433 * (moisture_at_baling - moisture_factor * dry_matter_at_baling / (1 - days_baled_adjuster))
        denominator = 

class ProtectedIndoors(Hay):
    """
    Represents protected indoors hay storage, a subclass of Hay.
    """

    pass


class ProtectedWrapped(Hay):
    """
    Represents protected wrapped hay storage, a subclass of Hay.
    """

    pass


class ProtectedTarped(Hay):
    """
    Represents protected tarped hay storage, a subclass of Hay.
    """

    pass


class Unprotected(Hay):
    """
    Represents unprotected hay storage, a subclass of Hay.
    """

    pass
