project:
  type: book

book:
  title: "Ruminant Farm Systems (RuFaS)"
  subtitle: "Scientific Documentation"
  date: "4/1/2026"
  search: true
  page-navigation: true
  chapters:
    - index.qmd
    - example_structures.qmd
    - animal.qmd
    - manure.qmd



bibliography: rufas.bib

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt
    pdf-engine: xelatex
    include-in-header: preamble.tex
    toc: true
    toc-depth: 2
    toc-title: "Contents"
    lof: true
    lot: true
    number-sections: true    
  epub:
    cover-image: rufas.png