project:
  type: book

book:
  title: "Ruminant Farm Systems (RuFaS)"
  subtitle: "Scientific Documentation"
  date: "4/1/2026"
  search: true
  page-navigation: true
  chapters:
    - index.qmd
    - example_structures.qmd
    - animal.qmd
    - manure.qmd



bibliography: rufas.bib

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    pdf-engine: xelatex
    documentclass: scrbook
    classoption:
      - oneside
      - openany
    papersize: letter
    margin-top: 1in
    margin-bottom: 1in
    margin-left: 1in
    margin-right: 1in
    toc: true
    toc-depth: 2
    toc-title: "Contents"
    lof: true
    lot: true
    number-sections: true
    keep-tex: true