from __future__ import annotations

import logging
import numbers
import re
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Callable

import numpy as np

from RUFAS.graph_generator import GraphGenerator
from RUFAS.post_processing.unit_handler import UnitHandler
from RUFAS.util import Aggregator, Utility

if TYPE_CHECKING:
    from RUFAS.rufas_time import RufasTime

AGGREGATION_FUNCTIONS: dict[str, Callable[[list[float]], float] | Callable[[list[float]], float | None]] = {
    "average": Aggregator.average,
    "division": Aggregator.division,
    "product": Aggregator.product,
    "SD": Aggregator.standard_deviation,
    "sum": Aggregator.sum,
    "subtraction": Aggregator.subtraction,
}


@dataclass
class ReportGeneratorConfig:
    """
    Configuration for ReportGenerator.

    Attributes
    ----------
    metadata_prefix : str, default ""
        The identifier for the metadata task being run, used for logging.
    time : RufasTime | None, default None
        A ``RufasTime`` object used to track the simulation time.
    """

    metadata_prefix: str = ""
    time: RufasTime | None = None


class ReportGenerator:
    """
    A class to generate reports based on filtered data and aggregation criteria and store them in a dictionary.

    Parameters
    ----------
    config : ReportGeneratorConfig
        Configuration dataclass for ReportGenerator.

    Attributes
    ----------
    reports : dict[str, dict[str, list[Any]]]
        A dictionary containing the generated reports, with the report name as the key and the report data as the value.
    metadata_prefix : str
        The identifier for the metadata task being run, used for logging.
    time : RufasTime | None
        A ``RufasTime`` object used to track the simulation time
    unit_handler : UnitHandler
        Handles the measurement units of the report data.

    Notes
    -----
    ReportGenerator consumes variables selected from OutputManager by filters. To inspect whether source variables were
    reported to OutputManager daily or on another cadence, use OutputManager's `report_variables_usage_counts()` output:
    `variables_usage_counts` shows filter selection counts, and `variables_not_reported_daily` lists variables treated
    as non-daily for reporting diagnostics with `variable_name` and `report_count` columns.
    """

    def __init__(self, config: ReportGeneratorConfig) -> None:
        """Initializes the ReportGenerator."""
        self.reports: dict[str, dict[str, list[Any]]] = {}
        self.metadata_prefix: str = config.metadata_prefix
        self.time: RufasTime | None = config.time
        self.unit_handler: UnitHandler = UnitHandler(config.metadata_prefix)
        # TODO use the RuFaS logger helpers once the new logging system is merged (#3192)
        self._logger: logging.Logger = logging.getLogger(f"RUFAS.{self.__class__.__name__}")

    def _log(self, level: int, name: str, message: str, function_name: str) -> None:
        """
        Logs a message directly to Python's logging system.

        Parameters
        ----------
        level : int
            The Python logging level of the message.
        name : str
            The name of the log, warning, or error.
        message : str
            The message to be logged.
        function_name : str
            The name of the function logging the message.
        """
        info_map = {
            "class": self.__class__.__name__,
            "function": function_name,
            "metadata_prefix": self.metadata_prefix,
        }
        self._logger.log(level, message, extra={"rufas_name": name, "rufas_info_map": info_map})

    def clear_reports(self) -> None:
        """Clears the reports generated by the ReportGenerator."""
        self.reports = {}

    def generate_report(
        self,
        filter_content: dict[str, Any],
        filtered_pool: dict[str, dict[str, list[Any]]],
    ) -> None:
        """
        Generates a report specified by the given filter content.

        Parameters
        ----------
        filter_content : dict[str, Any]
            A dictionary containing the configuration for the report, including details
            such as ``name``, ``filters``, ``cross_references``, and aggregation instructions.
        filtered_pool : dict[str, dict[str, list[Any]]]
            The data pool from which reports are generated.
        """

        individual_report_name = self._ensure_unique_report_name_with_timestamp(filter_content.get("name"))

        self._log(
            logging.INFO,
            "start_generate_individual_report",
            f"Start generating individual report: {individual_report_name}",
            self.generate_report.__name__,
        )

        try:
            report_pool = self._add_cross_references_to_pool(filter_content, filtered_pool)
            report_data, is_report_aggregated = self._perform_aggregations(report_pool, filter_content)
            if "data_significant_digits" in filter_content:
                report_data = Utility.round_numeric_values_in_dict(
                    report_data, filter_content["data_significant_digits"]
                )
            report_filter_data = self._name_report_columns(
                report_data, filter_content, individual_report_name, is_report_aggregated
            )
            self._store_or_graph_report_data(report_filter_data, filter_content, individual_report_name)

        except (KeyError, ValueError) as e:
            error_type = e.__class__.__name__
            self._log(
                logging.ERROR,
                "report_generation_error",
                f"Error generating report ({individual_report_name}) => {error_type}: {e}",
                self.generate_report.__name__,
            )

    def _add_cross_references_to_pool(
        self,
        filter_content: dict[str, Any],
        filtered_pool: dict[str, dict[str, list[Any]]],
    ) -> dict[str, dict[str, list[Any]]]:
        """
        Adds the previously generated reports that are cross-referenced in the filter content to the data pool.

        Parameters
        ----------
        filter_content : dict[str, Any]
            A dictionary containing the configuration for the report, including details
            such as ``name``, ``filters``, ``cross_references``, and aggregation instructions.
        filtered_pool : dict[str, dict[str, list[Any]]]
            The data pool from which reports are generated.

        Returns
        -------
        dict[str, dict[str, list[Any]]]
            The cross-referenced reports followed by the data in the filtered pool, or the filtered pool itself if the
            filter content has no ``cross_references``.

        Raises
        ------
        KeyError
            If any of the cross-referenced reports are missing.
        """
        if "cross_references" not in filter_content:
            return filtered_pool

        self._check_for_missing_references(filter_content["cross_references"])
        cross_reference_data = self._get_reports_by_regex(filter_content["cross_references"])
        cross_reference_data.update(filtered_pool)
        return cross_reference_data

    def _name_report_columns(
        self,
        report_data: dict[str, list[Any]],
        filter_content: dict[str, Any],
        individual_report_name: str,
        is_report_aggregated: bool,
    ) -> dict[str, dict[str, list[Any]]]:
        """
        Names the columns of the report data.

        Parameters
        ----------
        report_data : dict[str, list[Any]]
            The report data, with or without aggregation.
        filter_content : dict[str, Any]
            A dictionary containing the configuration for the report, including details
            such as ``name``, ``filters``, ``cross_references``, and aggregation instructions.
        individual_report_name : str
            The name of the report.
        is_report_aggregated : bool
            Whether the report data has been aggregated.

        Returns
        -------
        dict[str, dict[str, list[Any]]]
            The report data, with the unique name of each column as the key.

        Notes
        -----
        The report name alone is used when the report has a single column that was not aggregated and
        ``use_verbose_report_name`` is not set in the filter content. Otherwise, the column is named
        ``<report name>_<column>``. If the report name is empty, the column keeps its own name.
        """
        report_filter_data: dict[str, dict[str, list[Any]]] = {}
        for col, values in report_data.items():
            column_name = self._ensure_unique_report_name_with_timestamp(
                (individual_report_name if individual_report_name else col)
                if (
                    (not is_report_aggregated and not filter_content.get("use_verbose_report_name"))
                    and len(report_data) == 1
                )
                else (f"{individual_report_name}_{col}" if individual_report_name else col)
            )
            report_filter_data[column_name] = {"values": values}
        return report_filter_data

    def _store_or_graph_report_data(
        self,
        report_filter_data: dict[str, dict[str, list[Any]]],
        filter_content: dict[str, Any],
        individual_report_name: str,
    ) -> None:
        """
        Stores the report data in the generated reports and/or sends it to be graphed.

        Parameters
        ----------
        report_filter_data : dict[str, dict[str, list[Any]]]
            The report data, with the unique name of each column as the key.
        filter_content : dict[str, Any]
            A dictionary containing the configuration for the report, including details
            such as ``name``, ``filters``, ``cross_references``, and aggregation instructions.
        individual_report_name : str
            The name of the report.

        Notes
        -----
        Report data with ``graph_details`` in the filter content is graphed, and is only stored in the generated
        reports if ``graph_and_report`` is also set.
        """
        should_graph_report_data = filter_content.get("graph_details")
        enable_graph_and_report = filter_content.get("graph_and_report", False)
        if should_graph_report_data:
            if enable_graph_and_report:
                self.reports.update(report_filter_data)
            self._prepare_report_data_to_be_graphed(report_filter_data, filter_content, individual_report_name)
        else:
            self.reports.update(report_filter_data)
            if enable_graph_and_report:
                self._log(
                    logging.WARNING,
                    "report_generation_warning",
                    "Request to graph and report data not fulfilled "
                    "- no graph_details present in report filter file.",
                    self._store_or_graph_report_data.__name__,
                )

    def _get_horizontal_first_value(
        self,
        filter_content: dict[str, Any],
    ) -> bool:
        """
        Returns the value of ``horizontal_first`` or ``False`` as the default value.

        Parameters
        ----------
        filter_content : dict[str, Any]
            A dictionary containing the configuration for the report, including details such as ``name``, ``filters``,
            ``cross_references``, and aggregation instructions.

        Returns
        -------
        bool
            The value of ``horizontal_first`` in the report filter, or ``False`` if it is not present.
        """

        horizontal_first: bool = filter_content.get("horizontal_first", False)
        if not horizontal_first:
            return False

        return horizontal_first

    def _prepare_report_data_to_be_graphed(
        self, graph_data: dict[str, Any], filter_content: dict[str, Any], individual_report_name: str
    ) -> None:
        """
        Prepares and sends aggregated report data to ``GraphGenerator`` to be graphed.

        Parameters
        ----------
        graph_data : dict[str, Any]
            The report data to be graphed.
        filter_content : dict[str, Any]
            A dictionary containing the configuration for the report, including details
            such as ``name``, ``filters``, ``cross_references``, and aggregation instructions.
        individual_report_name : str
            The name of the report to be graphed.
        """

        # TODO use the overhauled GraphGenerator, which logs directly, once its functions are set up (#3190)
        graph_generator = GraphGenerator(filter_content["graph_details"]["metadata_prefix"], time=self.time)
        graph_details = {
            **filter_content["graph_details"],
            "title": filter_content["name"],
            "filters": filter_content["filters"],
            "is_aggregated_report_data": True,
        }
        graphics_dir = graph_details.pop("graphics_dir", None)
        produce_graphics = graph_details.get("produce_graphics", True)
        graph_generator.generate_graph(
            graph_data, graph_details, individual_report_name, graphics_dir, produce_graphics
        )

    def _ensure_unique_report_name_with_timestamp(self, report_name: str | None) -> str:
        """
        Makes the given report name unique. If it is not, append a timestamp to it.

        Parameters
        ----------
        report_name : str | None
            The name of the report.

        Returns
        -------
        str
            The unique name for the report.

        Notes
        -----
        The rules for generating the name are as follows:
        1. If the report name is ``None``, the name is set to ``untitled_<timestamp>``.
        2. If the name is already present in the list of previously generated reports, the timestamp is appended
            to the name to make it unique.
        3. Otherwise, return the report name as is.
        """

        if report_name is None:
            report_name = f"untitled_{Utility.get_timestamp(True)}"

        if report_name in self.reports:
            report_name = f"{report_name}_{Utility.get_timestamp(True)}"

        return report_name

    def _check_for_missing_references(self, references: list[str]) -> None:
        """
        Checks if all the referenced reports are present in the list of previously generated reports.

        Parameters
        ----------
        references : list[str]
            The list of report references to check.

        Raises
        ------
        KeyError
            If any of the report references are missing.
        """

        missing_references = []

        for ref in references:
            if not any(re.fullmatch(ref, report_name) for report_name in self.reports):
                missing_references.append(ref)

        if missing_references:
            raise KeyError(
                "Report Generator error: Missing referenced reports matching the following pattern(s): "
                f"{', '.join(missing_references)}"
            )

    def _get_reports_by_regex(self, regex_patterns: list[str]) -> dict[str, dict[str, list[Any]]]:
        """
        Retrieves reports based on matching the existing report names with the given regex patterns.

        Parameters
        ----------
        regex_patterns : list[str]
            A list of regex patterns to match with the existing report names.

        Returns
        -------
        dict[str, dict[str, list[Any]]]
            The matching reports.

        Notes
        -----
        Each pattern is checked for a full match against the report names. A "full match"
        means that the regex must match the entire string of the report name from start to finish,
        without partial matches. This reduces the potential for false positives.
        """

        matched_reports = {}
        for pattern in regex_patterns:
            for report_name in self.reports:
                if re.fullmatch(pattern, report_name):
                    matched_reports[report_name] = self.reports[report_name]
        return matched_reports

    def _perform_aggregations(
        self,
        filtered_pool: dict[str, dict[str, list[Any]]],
        filter_content: dict[str, Any],
    ) -> tuple[dict[str, list[Any]], bool]:
        """
        Fetches aggregation keys from the filter content and applies aggregation to the data.

        Parameters
        ----------
        filtered_pool : dict[str, dict[str, list[Any]]]
            The data pool from which the report is to be generated, structured as a dictionary.
        filter_content : dict[str, Any]
            A dictionary containing filter criteria, aggregation instructions, and scalar operation details.

        Returns
        -------
        tuple[dict[str, list[Any]], bool]
            - The aggregated report data.
                - If no aggregation is specified, all the columns will be returned.
                - If both horizontal and vertical aggregations are specified, the returned dictionary will have one key
                    that is either ``hor_ver_agg`` or ``ver_hor_agg`` depending on the value of the
                    ``horizontal_first`` key in the filter content.
                - If only horizontal aggregation is specified, the returned dictionary will have one key ``hor_agg``.
                - If only vertical aggregation is specified, the returned dictionary will have one key ``ver_agg``.
            - A boolean indicating whether the report data has been aggregated.

        Raises
        ------
        ValueError
            If there is an error preparing the report data.
            If the report data is empty.
        """
        (
            horizontal_agg_key,
            vertical_agg_key,
        ) = self._extract_aggregation_keys(filter_content)
        if filter_content.get("display_units", False):
            filtered_pool = self.unit_handler.add_var_units(filtered_pool)
        report_data: dict[str, list[Any]] = {key: filtered_pool[key]["values"] for key in filtered_pool}
        if not all(report_data[key] for key in report_data):
            raise ValueError(
                "Report Generator error: One or more columns in the report data are empty, "
                "cannot perform aggregations."
            )
        self._add_constants_to_report_data(report_data, filter_content)

        if not report_data:
            raise ValueError(
                f"Report Generator error: filter {filter_content.get('filters')} in {filter_content.get('name')} "
                "led to empty report data."
            )

        if not horizontal_agg_key and not vertical_agg_key:
            return report_data, False

        aggregate_report = self._route_aggregator_functions(
            report_data, filter_content, horizontal_agg_key, vertical_agg_key
        )

        return aggregate_report, True

    def _route_aggregator_functions(
        self,
        report_data: dict[str, list[Any]],
        filter_content: dict[str, Any],
        horizontal_agg_key: str | None = None,
        vertical_agg_key: str | None = None,
    ) -> dict[str, list[Any]]:
        """
        Routes report data to appropriate vertical and horizontal aggregator functions.

        Parameters
        ----------
        report_data : dict[str, list[Any]]
            The data to be aggregated.
        filter_content : dict[str, Any]
            The report filter settings.
        horizontal_agg_key : str | None, optional
            The horizontal aggregator function key.
        vertical_agg_key : str | None, optional
            The vertical aggregator function key.

        Returns
        -------
        dict[str, list[Any]]
            The aggregated data.
        """
        aggregate_report: dict[str, list[Any]] = report_data

        if horizontal_agg_key and vertical_agg_key:
            aggregate_report = self._handle_horizontal_and_vertical_aggregations(
                report_data, horizontal_agg_key, vertical_agg_key, filter_content
            )

        elif horizontal_agg_key:
            aggregate_report = self._handle_horizontal_only_aggregation(report_data, horizontal_agg_key, filter_content)

        elif vertical_agg_key:
            aggregate_report = self._handle_vertical_only_aggregation(report_data, vertical_agg_key, filter_content)

        self._log(
            logging.INFO,
            f"Report '{filter_content.get('name', 'Unnamed Report')}' aggregation variables.",
            f"Variables/constants aggregated: {list(report_data.keys())}.",
            self._route_aggregator_functions.__name__,
        )

        return aggregate_report

    def _handle_horizontal_only_aggregation(
        self,
        report_data: dict[str, list[Any]],
        horizontal_agg_key: str,
        filter_content: dict[str, Any],
    ) -> dict[str, list[Any]]:
        """
        Handles the horizontal aggregation of report data that is not aggregated vertically.

        Parameters
        ----------
        report_data : dict[str, list[Any]]
            The report data to be aggregated.
        horizontal_agg_key : str
            The key for the horizontal aggregation function.
        filter_content : dict[str, Any]
            A dictionary containing filter criteria, aggregation instructions, and scalar operation details.

        Returns
        -------
        dict[str, list[Any]]
            The aggregated report data, with ``hor_agg`` followed by the aggregated units, if they are displayed, as
            the only key.
        """
        horizontal_aggregator = AGGREGATION_FUNCTIONS[horizontal_agg_key]
        loop_list = filter_content.get("horizontal_order", list(report_data.keys()))
        horizontally_aggregated, aggregated_units = self._apply_horizontal_aggregation(
            report_data, loop_list, horizontal_aggregator, filter_content.get("simplify_units", True)
        )
        if filter_content.get("display_units", False):
            return {f"hor_agg_({aggregated_units})": horizontally_aggregated}
        else:
            return {"hor_agg": horizontally_aggregated}

    def _handle_vertical_only_aggregation(
        self,
        report_data: dict[str, list[Any]],
        vertical_agg_key: str,
        filter_content: dict[str, Any],
    ) -> dict[str, list[Any]]:
        """
        Handles the vertical aggregation of report data that is not aggregated horizontally.

        Parameters
        ----------
        report_data : dict[str, list[Any]]
            The report data to be aggregated.
        vertical_agg_key : str
            The key for the vertical aggregation function.
        filter_content : dict[str, Any]
            A dictionary containing filter criteria, aggregation instructions, and scalar operation details.

        Returns
        -------
        dict[str, list[Any]]
            The aggregated report data.
                - If there are multiple columns, each key is the name of the column with ``_ver_agg`` added to it.
                - If there is a single column, the key is ``ver_agg``, or the name of the column with ``_ver_agg``
                    added to it when ``use_verbose_report_name`` is set in the filter content.
                - If units are displayed, they are kept at the end of the key.
        """
        aggregate_report: dict[str, list[Any]]
        vertical_aggregator = AGGREGATION_FUNCTIONS[vertical_agg_key]
        vertically_aggregated = self._apply_vertical_aggregation(report_data, vertical_aggregator)

        has_multiple_columns = len(vertically_aggregated) > 1
        if filter_content.get("display_units", False):
            if has_multiple_columns:
                aggregate_report = {self._update_key(key): value for key, value in vertically_aggregated.items()}
            else:
                units = re.search(r"\(.*\)", next(iter(report_data)))
                column_name = (
                    f"{next(iter(vertically_aggregated))}_ver_agg"
                    if filter_content.get("use_verbose_report_name")
                    else "ver_agg"
                )
                if units is not None:
                    aggregate_report = {f"{column_name}_{units.group(0)}": list(vertically_aggregated.values())[0]}
                else:
                    aggregate_report = {f"{column_name}": list(vertically_aggregated.values())[0]}
        else:
            if has_multiple_columns:
                aggregate_report = {f"{key}_ver_agg": value for key, value in vertically_aggregated.items()}
            else:
                column_name = (
                    f"{next(iter(vertically_aggregated))}_ver_agg"
                    if filter_content.get("use_verbose_report_name")
                    else "ver_agg"
                )
                aggregate_report = {column_name: list(vertically_aggregated.values())[0]}
        return aggregate_report

    @staticmethod
    def _update_key(key: str) -> str:
        """
        Updates dictionary keys to keep units at the end of the key.

        Parameters
        ----------
        key : str
            The key to be updated

        Returns
        -------
        str
            The updated key.
        """
        match = re.search(r"\(.*?\)", key)
        if match:
            units = match.group(0)
            base_key = key[: match.start()].strip()
            updated_key = f"{base_key}_ver_agg_{units}"
        else:
            updated_key = f"{key}_ver_agg"
        return updated_key

    @staticmethod
    def _get_aggregator_key(
        aggregator: Callable[[list[float]], float] | Callable[[list[float]], float | None],
    ) -> str | None:
        """
        Gets the key of the given aggregation function.

        Parameters
        ----------
        aggregator : Callable[[list[float]], float] | Callable[[list[float]], float | None]
            The aggregation function to get the key of.

        Returns
        -------
        str | None
            The key of the aggregation function, or ``None`` if it is not one of the supported aggregation functions.
        """
        aggregator_key = None
        for key, function in AGGREGATION_FUNCTIONS.items():
            if function == aggregator:
                aggregator_key = key
                break
        return aggregator_key

    def _handle_horizontal_and_vertical_aggregations(
        self,
        aggregate_report: dict[str, list[Any]],
        horizontal_agg_key: str,
        vertical_agg_key: str,
        filter_content: dict[str, Any],
    ) -> dict[str, list[Any]]:
        """
        Handles both horizontal and vertical aggregations on the report data.

        Parameters
        ----------
        aggregate_report : dict[str, list[Any]]
            The report data to be aggregated.
        horizontal_agg_key : str
            The key for the horizontal aggregation function.
        vertical_agg_key : str
            The key for the vertical aggregation function.
        filter_content : dict[str, Any]
            A dictionary containing filter criteria, aggregation instructions, and scalar operation details.

        Returns
        -------
        dict[str, list[Any]]
            The aggregated report data.
        """

        horizontal_first = self._get_horizontal_first_value(filter_content)
        horizontal_aggregator = AGGREGATION_FUNCTIONS[horizontal_agg_key]
        vertical_aggregator = AGGREGATION_FUNCTIONS[vertical_agg_key]
        display_units = filter_content.get("display_units", False)
        simplify_units = filter_content.get("simplify_units", True)
        aggregate_report_keys = ", ".join(f"'{key}'" for key in aggregate_report)
        if horizontal_first:
            loop_list = filter_content.get("horizontal_order", list(aggregate_report.keys()))
            horizontally_aggregated, aggregate_units = self._apply_horizontal_aggregation(
                aggregate_report, loop_list, horizontal_aggregator, simplify_units
            )
            vertically_aggregated_data = self._handle_aggregation(
                vertical_aggregator, horizontally_aggregated, aggregate_report_keys
            )
            if display_units:
                aggregate_report = {f"hor_ver_agg_({aggregate_units})": [vertically_aggregated_data]}
            else:
                aggregate_report = {"hor_ver_agg": [vertically_aggregated_data]}
        else:
            vertically_aggregated = self._apply_vertical_aggregation(aggregate_report, vertical_aggregator)
            ver_hor_aggregated = []
            for elements in zip(*vertically_aggregated.values()):
                horizontally_aggregated_data = self._handle_aggregation(
                    horizontal_aggregator, list(elements), aggregate_report_keys
                )
                ver_hor_aggregated.append(horizontally_aggregated_data)
            aggregate_units = self.unit_handler.aggregate_units(
                vertically_aggregated, self._get_aggregator_key(horizontal_aggregator), simplify_units
            )
            if display_units:
                aggregate_report = {f"ver_hor_agg_({aggregate_units})": ver_hor_aggregated}
            else:
                aggregate_report = {"ver_hor_agg": ver_hor_aggregated}
        return aggregate_report

    def _extract_aggregation_keys(self, filter_content: dict[str, Any]) -> tuple[str | None, str | None]:
        """
        Extracts horizontal and vertical aggregation keys from the filter content.

        Parameters
        ----------
        filter_content : dict[str, Any]
            A dictionary containing filter criteria, aggregation instructions, and scalar operation details.
            It should include keys for ``horizontal_aggregation`` and ``vertical_aggregation`` if applicable.

        Returns
        -------
        tuple[str | None, str | None]
            - The extracted horizontal aggregation key, or None if not specified.
            - The extracted vertical aggregation key, or None if not specified.

        """

        horizontal_agg_key = filter_content.get("horizontal_aggregation")
        vertical_agg_key = filter_content.get("vertical_aggregation")

        return horizontal_agg_key, vertical_agg_key

    def _apply_horizontal_aggregation(
        self,
        report_data: dict[str, list[Any]],
        loop_list: list[str],
        aggregator: Callable[[list[float]], float] | Callable[[list[float]], float | None],
        simplify_units: bool,
    ) -> tuple[list[Any], str]:
        """
        Performs horizontal aggregation on report data using a specified aggregator function.

        Parameters
        ----------
        report_data : dict[str, list[Any]]
            The data pool to be aggregated, structured as a dictionary of lists.
        loop_list : list[str]
            List of keys indicating the order in which to aggregate data.
        aggregator : Callable[[list[float]], float] | Callable[[list[float]], float | None]
            The aggregation function to be used.
        simplify_units : bool
            Whether to reduce the units.

        Returns
        -------
        tuple[list[Any], str]
            - The aggregated data.
            - The aggregated units.

        Raises
        ------
        ValueError
            If the data to be aggregated has different lengths.

        """

        lengths = [len(report_data[key]) for key in report_data if any(loop_key in key for loop_key in loop_list)]
        if len(set(lengths)) != 1:
            raise ValueError("Report Generator error: Can't aggregate data with different lengths")
        max_length = max(lengths)
        aggregated_data: list[Any] = []
        report_data_keys = ", ".join(f"'{key}'" for key in report_data)
        for i in range(max_length):
            temp_data = [report_data[key][i] for loop_key in loop_list for key in report_data if loop_key in key]
            horizontally_aggregated_data = self._handle_aggregation(aggregator, temp_data, report_data_keys)
            aggregated_data.append(horizontally_aggregated_data)
        ordered_report_data = {
            key: report_data[key] for ordered_key in loop_list for key in report_data if ordered_key in key
        }
        aggregated_units = self.unit_handler.aggregate_units(
            ordered_report_data, self._get_aggregator_key(aggregator), simplify_units
        )
        return aggregated_data, aggregated_units

    def _apply_vertical_aggregation(
        self,
        report_data: dict[str, list[Any]],
        aggregator: Callable[[list[float]], float] | Callable[[list[float]], float | None],
    ) -> dict[str, list[Any]]:
        """
        Performs vertical aggregation on report data using a specified aggregator function.

        Parameters
        ----------
        report_data : dict[str, list[Any]]
            The data pool to be aggregated, structured as a dictionary of lists.
        aggregator : Callable[[list[float]], float] | Callable[[list[float]], float | None]
            The aggregation function to be used.

        Returns
        -------
        dict[str, list[Any]]
            The aggregated data.

        """

        aggregated_data: dict[str, list[Any]] = {}
        for key, data in report_data.items():
            vertically_aggregated_data = self._handle_aggregation(aggregator, data, key)
            aggregated_data[key] = [vertically_aggregated_data]
        return aggregated_data

    def _handle_aggregation(
        self,
        aggregator: Callable[[list[float]], float] | Callable[[list[float]], float | None],
        data: list[float],
        key: str,
    ) -> float | None:
        """
        Wrapper function for ``ReportGenerator`` aggregators to catch ``None``s and ``NaN``s.

        Parameters
        ----------
        aggregator : Callable[[list[float]], float] | Callable[[list[float]], float | None]
            The aggregator function being called from the report filter.
        data : list[float]
            The data to be aggregated.
        key : str
            The key for the data being aggregated.

        Returns
        -------
        float | None
            The aggregated data. If the data contains any values that cannot be aggregated, an error is logged and
            ``None`` is returned.

        """
        aggregated_data = None
        if any(not isinstance(x, numbers.Real) or np.isnan(x) for x in data):
            self._log(
                logging.ERROR,
                "ReportGenerator aggregation error",
                f"Encountered unaggregatable values in variable(s): {key}. Returning None instead.",
                self._handle_aggregation.__name__,
            )
            return aggregated_data

        try:
            aggregated_data = aggregator(data)
        except Exception as e:
            self._log(
                logging.ERROR,
                "ReportGenerator aggregation error",
                f"Error during aggregation of {key} data: {str(e)}, returning None instead.",
                self._handle_aggregation.__name__,
            )
            return aggregated_data

        return aggregated_data

    def _add_constants_to_report_data(self, report_data: dict[str, list[Any]], filter_content: dict[str, Any]) -> None:
        """
        Adds constants to the report data.

        Parameters
        ----------
        report_data : dict[str, list[Any]]
            The data to which constants need to be added.
        filter_content : dict[str, Any]
            A dictionary containing filter criteria, aggregation instructions, and scalar operation details.

        Raises
        ------
        ValueError
            If the name or value of any constant is not valid.

        Examples
        --------
        An example of a configuration for constants:
        .. code-block:: python

            "constants": {
                "Kilograms to Pounds": 2.20462,
                "Pounds to Dollars": 10
            }

        """
        constants_config = filter_content.get("constants")
        if not constants_config:
            return

        self._validate_constants(report_data, constants_config)

        if filter_content.get("display_units", False):
            constants_config = self.unit_handler.add_units_to_constants(constants_config)

        max_length = max([len(lst) for lst in report_data.values()])
        for name, value in constants_config.items():
            report_data[name] = [value] * max_length

    def _validate_constants(
        self,
        existing_reports: dict[str, list[Any]],
        constants_config: dict[str, int | float],
    ) -> None:
        """
        Validates the names and values of the constants in the ``constants_config``.

        This method checks that each constant's name is not ``None``, a non-empty string, and
        is unique compared to the names of all the existing reports. It also verifies that
        each constant's value is a number (``int`` or ``float``) and not ``None``.

        Parameters
        ----------
        existing_reports : dict[str, list[Any]]
            The dictionary containing the names and values of the reports that have already been generated.
        constants_config : dict[str, int | float]
            A dictionary containing the names and values of the constants to be added to the report data.

        Raises
        ------
        ValueError
            If a constant name already exists in the report data.
            If a constant name or value is ``None``.
            If a constant name is not a string.
            If a constant name is empty.
            If a constant value is not a number.
        """

        for name, value in constants_config.items():
            if name in existing_reports:
                raise ValueError(f"Report Generator error: Constant name {name} already exists in report data.")

            if name is None:
                raise ValueError("Report Generator error: Constant name cannot be None.")

            if value is None:
                raise ValueError("Report Generator error: Constant value cannot be None.")

            if not isinstance(name, str):
                raise ValueError(f"Report Generator error: Constant name {name} must be a string and cannot be empty.")

            if len(name) == 0:
                raise ValueError(f"Report Generator error: Constant name {name} cannot be empty.")

            if not isinstance(value, (int, float)):
                raise ValueError(f"Report Generator error: Constant value {value} must be a number.")
