sequenceDiagram
    autonumber
    participant S as SimulationEngine
    participant N as Non-Manure Modules
    participant M as Manure Module
    participant MM as ManureManagement
    participant MSC as Manure Subcomponents

    activate S
    loop Every day of simulation
        S->>N: calls daily_animal_routine() on animal module
        deactivate S

        activate N
        N->>S: Done!
        deactivate N

        activate S
        S->>M: calls simulate_daily_manure_management() on manure module
        deactivate S
        activate M
        M->>MM: calls daily_update() manure management
        deactivate M

        activate MM
        loop Every animal pen
            MM->>MSC: creates a manure management pen
            deactivate MM
            activate MSC
            MSC->>MM: Done!
            deactivate MSC

            activate MM
            MM->>MSC: calls daily_update() on a manure handler
            deactivate MM
            activate MSC
            MSC->>MM: returns a manure handler daily output
            deactivate MSC

            activate MM
            MM->>MSC: calls daily_update() on a reception pit
            deactivate MM
            activate MSC
            MSC->>MM: returns a reception pit daily output
            deactivate MSC

            activate MM
            opt is a digester present?
                MM->>MSC: calls daily_update() on an anaerobic digester
                deactivate MM
                activate MSC
                MSC->>MM: returns an anaerobic digestion daily output
                deactivate MSC
            end

            activate MM
            MM->>MSC: calls daily_update() on a manure separator
            deactivate MM
            activate MSC
            MSC->>MM: returns a manure separator daily output
            deactivate MSC

            activate MM
            opt is a digester present?
                MM->>MSC: calls daily_update() on an anaerobic digester
                deactivate MM
                activate MSC
                MSC->>MM: returns an anaerobic digestion daily output
                deactivate MSC
            end

            activate MM
            MM->>MSC: calls daily_update() on a manure treatment
            deactivate MM
            activate MSC
            MSC->>MM: returns a manure treatment daily output & accumulated output
            deactivate MSC

            activate MM
            MM->>MSC: calls daily_update() on a manure treatment
            deactivate MM
            activate MSC
            MSC->>MM: returns a manure treatment daily output & accumulated output
            deactivate MSC

            activate MM
            MM->>MSC: appends daily output data
            deactivate MM
            activate MSC
            MSC->>MM: Done!
            deactivate MSC
        end

        activate MM
        opt is last day of simulation?
            MM->>MSC: exports data and produces graphics
            deactivate MM
            activate MSC
            MSC->>MM: Done!
            deactivate MSC
        end
        activate MM
        MM->>M: Done!
        deactivate MM

        activate M
        M->>S: Done!
        deactivate M

        activate S
        S->>N: calls daily_fields_routine() on soil and crop module
        deactivate S
        activate N
        N->>S: Done!
        deactivate N

        activate S
        S->>N: calls daily_feed_routine() on feed module
        deactivate S
        activate N
        N->>S: Done!
        deactivate N

        activate S
        S->>N: calls daily_update() on output handler
        deactivate S
        activate N
        N->>S: Done!
        deactivate N
    end
    activate S
    deactivate S
