sequenceDiagram
    participant DU as daily_updates()
    participant LCM as self.life_cycle_manager

    activate DU
    opt is simulating animals?
        DU->>LCM: calls daily_update()
        deactivate DU
        activate LCM
        LCM->>DU: returns various animals animals_added, animals_removed, calves_born, calves, heiferIs, heiferIIs, heiferIIIs, cows
    end