"""
RUFAS: Ruminant Farm Systems Model

File name: manure_handler_classes.py

Description:

Author(s):  William Donovan, wmdonovan@wisc.edu
            Yunus Mohammed, ymm26@cornell.edu
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict
from typing import List
from typing import Optional
from typing import Type

from RUFAS.routines.manure.default_enum.default_enum import DefaultEnum
from RUFAS.routines.manure.manure_handlers.bedding_classes import BeddingFactory
from RUFAS.routines.manure.manure_handlers.manure_handler_daily_output import ManureHandlerDailyOutput
from RUFAS.routines.manure.manure_handlers.milking_center import MilkingCenter
from RUFAS.routines.manure.pen.manure_management_pen import ManureManagementPen


class ManureHandlerType(DefaultEnum):
    """Enumerates the different types of manure handlers."""
    FLUSH_SYSTEM = 'flush system'
    MANUAL_SCRAPING = 'manual scraping'
    ALLEY_SCRAPER = 'alley scraper'
    DEFAULT = FLUSH_SYSTEM


class BaseManureHandler:
    """Base class for all manure handlers.

    Attributes:
        config: A ManureHandlerConfig object that specifies default data specific to the choice of
            manure handler.
        bedding: A Bedding object that specifies the type of bedding used.
        milking_center: A MilkingCenter object that handles relevant calculations
            related to the time lactating cows spent there.
        all_output: A list of ManureHandlerDailyOutput objects that stores the daily output of the
            manure handler.

    """

    def __init__(self,
                 bedding_type_name: str,
                 manure_handler_config: ManureHandlerConfig):
        """Initialize a BaseManureHandler object.

        Args:
            bedding_type_name: The name of the bedding type.
            manure_handler_config: A ManureHandlerInitData object that specifies default data
                specific to the choice of manure handler.

        """
        self.config = manure_handler_config
        self.bedding = BeddingFactory.get_instance(bedding_type_name)
        self.milking_center = MilkingCenter()
        self.all_output: List[ManureHandlerDailyOutput] = []

    @property
    def last_output(self) -> Optional[ManureHandlerDailyOutput]:
        """Return the last daily output data generated by the last daily_update() call.

        Returns:
            The last daily output data generated by the last daily_update() call.
            If there is no previous data generated, return None.

        """
        return self.all_output[-1] if len(self.all_output) > 0 else None

    def daily_update(self, pen: ManureManagementPen, sim_day: int) -> ManureHandlerDailyOutput:
        """Calculate and store the daily output of the manure handler.

        Note:
            "pseudocode_manure_management" MS.3

        Args:
            pen: A ManureManagementPen object.
            sim_day: The current simulation day.

        Returns:
            A ManureHandlerDailyOutput object.

        """
        daily_output = ManureHandlerDailyOutput(
                simulation_day=sim_day,
                pen_id=pen.id,
                urea=pen.manure.urea,
                TAN=pen.manure.TAN,
                N=pen.manure.N,
                TS=pen.manure.TS,
                VSd=pen.manure.VSd,
                VSnd=pen.manure.VSnd,
                P=pen.manure.P,
                K=pen.manure.K,
                manure_volume=pen.manure_volume,
                cleaning_water_volume=self.cleaning_water_volume_in_main_barn(pen),
                total_bedding_volume=self.bedding.total_bedding_volume(pen),
                total_water_volume_in_milking_center=self.milking_center.total_water_volume_used_in_milking_center(
                        pen)
        )
        self.all_output.append(daily_output)
        return daily_output

    def cleaning_water_volume_in_main_barn(self, pen: ManureManagementPen) -> float:
        """Calculate the volume of cleaning water needed for all the animals in pen.

        Args:
            pen: A ManureManagementPen object.

        Returns:
            Volume of cleaning water needed for the given pen, L.

        """
        return pen.num_animals * self.config.cleaning_water_use_rate


class FlushSystem(BaseManureHandler):
    """A class that handles calculations related to a flush system.

    Attributes:
        All inherited from BaseManureHandler.

    """
    pass


class ManualScraping(BaseManureHandler):
    """A class that handles calculations related to manual scraping.

    Attributes:
        All inherited from BaseManureHandler.

    """
    pass


class AlleyScraper(BaseManureHandler):
    """A class that handles calculations related to an alley scraper.

    Attributes:
        All inherited from BaseManureHandler.

    """
    pass


@dataclass
class ManureHandlerConfig:
    """Class for storing the configuration of a manure handler.

    Attributes:
        cleaning_water_use_rate: Amount of cleaning water used per animal per day, L.
        minutes_per_cleaning: Number of minutes needed per animal per cleaning, minutes.
        cleanings_per_day: Number of cleanings per day.

    """
    cleaning_water_use_rate: float = 0.0
    minutes_per_cleaning: int = 8
    cleanings_per_day: int = 2


class DefaultManureHandlerConfigFactory:
    """Class for creating default manure handler configurations."""

    FLUSH_SYSTEM_CONFIG = ManureHandlerConfig(
            cleaning_water_use_rate=757.0,
    )
    MANUAL_SCRAPING_CONFIG = ManureHandlerConfig(
            cleaning_water_use_rate=10.0,
    )
    ALLEY_SCRAPER_CONFIG = ManureHandlerConfig(
            cleaning_water_use_rate=10.0,
    )

    @classmethod
    def get_instance(cls, manure_handler_type: ManureHandlerType):
        """Return a default manure handler configuration for the given manure handler type.

        Args:
            manure_handler_type: The type of manure handler.

        Returns:
            A default ManureHandlerConfig object for the given manure handler type.

        """
        manure_handler_config_by_type = {
            ManureHandlerType.FLUSH_SYSTEM: cls.FLUSH_SYSTEM_CONFIG,
            ManureHandlerType.MANUAL_SCRAPING: cls.MANUAL_SCRAPING_CONFIG,
            ManureHandlerType.ALLEY_SCRAPER: cls.ALLEY_SCRAPER_CONFIG
        }
        return manure_handler_config_by_type[manure_handler_type]


class ManureHandlerFactory:
    """A class that contains the logic for creating different types of manure handlers."""

    @classmethod
    def get_instance(cls,
                     manure_handler_type_name: str,
                     bedding_type_name: str,
                     manure_handler_config: Optional[ManureHandlerConfig] = None) \
            -> BaseManureHandler:
        """Return an instance of a specific subtype of BaseManureHandler.

        Args:
            manure_handler_type_name: A string that specifies the type of manure handler.
            bedding_type_name: A string that specifies the type of bedding.
            manure_handler_config: A ManureHandlerConfig object that contains
                custom initialization data.

        Returns:
            A new instance of a BaseManureHandler subtype.

        """
        manure_handler_class_by_type: Dict[ManureHandlerType, Type[BaseManureHandler]] = {
            ManureHandlerType.FLUSH_SYSTEM: FlushSystem,
            ManureHandlerType.ALLEY_SCRAPER: AlleyScraper,
            ManureHandlerType.MANUAL_SCRAPING: ManualScraping,
        }

        manure_handler_type = ManureHandlerType.get_type(manure_handler_type_name)
        manure_handler_class = manure_handler_class_by_type[manure_handler_type]

        if manure_handler_config:
            return manure_handler_class(bedding_type_name, manure_handler_config)
        else:
            default_manure_handler_config = DefaultManureHandlerConfigFactory.get_instance(
                    manure_handler_type)
            return manure_handler_class(bedding_type_name, default_manure_handler_config)
