project:
  type: book

book:
  title: "mybook"
  author: "Jane Doe"
  date: "8/18/2021"
  chapters:
   
    - index.qmd
    - equations.qmd
    - animal.qmd



bibliography: rufas.bib

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt
    pdf-engine: xelatex
    include-in-header: preamble.tex
    toc: true
    toc-depth: 2
    toc-title: "Contents"
    lof: true
    lot: true
    number-sections: true    
  epub:
    cover-image: rufas.png