
# Equation examples (from Animal Documentation)

## Nutrient Requirements of Dairy Cattle (NRC) {#sec-nrc}

**Energy Requirements** For details about the variables included in each 
calculation, please refer to the [energykey](energy requirements key).

* **_Maintenance_** - The maintenance requirement is calculated based on metabolic body weight (body weight$^{0.75}$).

  [Lactating and Dry Cows]{.underline}
  
  $$CBW = MW * 0.06275$$ {#eq-nrc-cbw}
  
  $$ CW = {(18 + (DOP - 190) * 0.665) * (\frac{CBW}{45}),\text{if}DOP > 190.0} $$ {#eq-nrc-cw}
  
  *Otherwise*
  
  $$ NEmaint = 0.08 \times (BW - CW)^{0.75} $$ {#eq-nrc-ne-maint}

## Reformatted equations

@eq-nrc-cbw may be visually improved by using the `\times` LaTeX
command: 

$$CBW = MW \times 0.06275$$

## Use alphanumeric equation labels

Though quarto does not allow custom cross-reference labels, you can
include your own non-CR label with the \\tag latex command. *And* the
equation can still be cross-referenceable (and assigned a dynamic 
equation number) by using a custom cross-reference class (defined in _quarto.yml):

:::{#eqn-an-nrc-2}
$$ CBW = MW * 0.06275 \tag{\textbf{AN.NRC.2}}$$
:::

see @eqn-an-nrc-2



## Other equation Templates
<!-- Inline equations -->
The energy balance is $E = mc^2$.

<!-- display centered, on its own line 
gets numbered automatically in PDF 
Referencing equations - start with creating a label -->

$$
\begin{equation}
E = mc^2
\end{equation}
$$ {#eq-energy}

<!-- reference that label -->
See Equation @eq-energy.
<!-- additional example -->
$$
\begin{equation}
\text{nutrient\_proportion\_to\_be\_removed} =
\min\left(
\frac{\text{mass\_requested\_nutrient}}{\text{manure\_nutrient\_available}},
1
\right)
\end{equation}
$$ {#eq-nutrient-proportion}