from RUFAS.data_structures.crop_soil_to_feed_storage_connection import CropCategory, StorageType
from RUFAS.routines.field.crop.crop_data import PlantCategory
from RUFAS.routines.field.crop.crop_data_factory import CropConfiguration


SAMPLE_CROP_CONFIGURATION = CropConfiguration(
    name="alfalfa_silage",
    plant_category=PlantCategory.PERENNIAL_LEGUME,
    crop_category=CropCategory.ALFALFA,
    rufas_ids=[104, 109, 110],
    is_nitrogen_fixer=True,
    minimum_temperature=4.0,
    optimal_temperature=25.0,
    potential_heat_units=400.0,
    max_leaf_area_index=4.0,
    first_heat_fraction_point=0.15,
    first_leaf_fraction_point=0.01,
    second_heat_fraction_point=0.50,
    second_leaf_fraction_point=0.95,
    senescent_heat_fraction=0.90,
    light_use_efficiency=20.0,
    emergence_nitrogen_fraction=0.0417,
    half_mature_nitrogen_fraction=0.0290,
    mature_nitrogen_fraction=0.0200,
    emergence_phosphorus_fraction=0.0035,
    half_mature_phosphorus_fraction=0.0028,
    mature_phosphorus_fraction=0.0020,
    max_root_depth=3000,
    root_distribution_param_da=207.0,
    root_distribution_param_c=-1.032,
    storage_type=StorageType.BUNKER,
    optimal_harvest_index=0.90,
    minimum_harvest_index=0.40,
    dry_matter_percentage=42.883,
    lignin_dry_matter_percentage=7.419,
    crude_protein_percent=20.471,
    non_protein_nitrogen=10.098,
    starch=1.973,
    adf=33.683,
    ndf=43.195,
    sugar=6.274,
    ash=10.597,
    yield_nitrogen_fraction=0.0327536,
    yield_phosphorus_fraction=0.00351,
)
