class GeneralConstants:
    LITERS_TO_CUBIC_METERS = 0.001
    KG_TO_CUBIC_METERS = 0.001
    GRAMS_TO_KG = 0.001


    DAYS_PER_YEAR = 365
    SECONDS_PER_DAY = 86400

    WATER_DENSITY_KG_PER_LITER = 0.997
    WATER_DENSITY_KG_PER_M3 = WATER_DENSITY_KG_PER_LITER * LITERS_TO_CUBIC_METERS
