from RUFAS.input_manager import InputManager
from RUFAS.time import Time
from RUFAS.output_manager import OutputManager
import numpy as np
from scipy.integrate import quad


"""
Constant that is used to determine whether cows are considered to be milking twice or thrice daily when determining how
to adjust the lactation curve parameters.
"""
MILKING_FREQUENCY_THRESHOLD = 2.5

"""
Constants used to scale the adjustments for Wood's m and n parameters, respectively, before using them to the adjust
parameters.
"""
M_ADJUSTMENT_SCALING_FACTOR = 1e-2
N_ADJUSTMENT_SCALING_FACTOR = 1e-4


class LactationCurve:
    """
    Class that represents the lacatation curve of the simulated farm.
    Obtains the necessary inputs from existing data collected in the simulation.

    ...

    Attributes
    ----------
    year: string
        The year which the simulation will end.
    region: string | None
        One of the 13 possible geographic regions or 'None' if the location is not included in the dataset.
    annual_MY_lbs: int | None
        The observed total milk yield generated by the farm in one year in lbs.
    parity_percentages: list
        Percentages of total herd represented by parity 1, 2, and 3+.
    num_milking_cows: float
        Number of milking cows in the herd. Calculated using the number of cows and assumed milking cow percentage.
    milking_freq : string
        The average or most common number of times cows are milked per day (1, 2, or 3 times daily)
    parity2_MilkYield305_adj: int
        The parity 2 milk adjustment value for the 305 day milk yield
    parity3_MilkYield305_adj: int
        The parity 3 adjustment value for the 305 day milk yield
    adjustment_dict: dict

    """

    def __init__(self, time: Time) -> None:
        im = InputManager()
        self.om = OutputManager()

        lactation_inputs = im.get_data("lactation")
        all_year_adjustments = lactation_inputs["adjustments"]["year"]
        year_adjustments = self._get_year_adjustments(all_year_adjustments, time)

        fips_code = im.get_data("config.FIPS_county_code")
        all_region_adjustments = lactation_inputs["adjustments"]["region"]
        region_mapping = lactation_inputs["state_to_region_mapping"]
        region_adjustments = self._get_region_adjustments(all_region_adjustments, region_mapping, fips_code)

        animal_inputs = im.get_data("animal")
        animal_milking_frequency = animal_inputs["animal_config"]["management_decisions"]["cow_times_milked_per_day"]
        all_milking_frequency_adjustments = lactation_inputs["adjustments"]["milking_frequency"]
        milking_frequency_adjustments = self._get_milking_frequency_adjustments(
            all_milking_frequency_adjustments, animal_milking_frequency
        )

        parity_adjustments = lactation_inputs["adjustments"]["parity"]

        base_wood_parameter_l = lactation_inputs["parameter_mean_values"]["parameter_l_mean"]
        base_wood_parameter_m = lactation_inputs["parameter_mean_values"]["parameter_m_mean"]
        base_wood_parameter_n = lactation_inputs["parameter_mean_values"]["parameter_n_mean"]

        self.parity_one_parameters = self._calculate_adjusted_wood_parameters(
            base_wood_parameter_l,
            base_wood_parameter_m,
            base_wood_parameter_n,
            [parity_adjustments["1"], year_adjustments, region_adjustments, milking_frequency_adjustments],
        )

        self.parity_two_parameters = self._calculate_adjusted_wood_parameters(
            base_wood_parameter_l,
            base_wood_parameter_m,
            base_wood_parameter_n,
            [parity_adjustments["2"], year_adjustments, region_adjustments, milking_frequency_adjustments],
        )

        self.parity_three_parameters = self._calculate_adjusted_wood_parameters(
            base_wood_parameter_l,
            base_wood_parameter_m,
            base_wood_parameter_n,
            [parity_adjustments["3"], year_adjustments, region_adjustments, milking_frequency_adjustments],
        )

        self.l_param_std_dev = lactation_inputs["parameter_standard_deviations"]["parameter_l_std_dev"]
        self.m_param_std_dev = lactation_inputs["parameter_standard_deviations"]["parameter_m_std_dev"]
        self.n_param_std_dev = lactation_inputs["parameter_standard_deviations"]["parameter_n_std_dev"]

        self.annual_MY_lbs = im.get_data("animal.herd_information.annual_milk_yield_lbs")  # int or None
        self.parity_percentages = im.get_data("animal.herd_information.parity_percentages")  # list of 3 floats
        self.num_milking_cows = (
            im.get_data("animal.herd_information.cow_num") * lactation_inputs["assumed_milking_cow_percentage"]
        )

        self.parity2_MilkYield305_adj = lactation_inputs["parity_milk_adjustments"]["parity2_MilkYield305_adjustment"]
        self.parity3_MilkYield305_adj = lactation_inputs["parity_milk_adjustments"]["parity3_MilkYield305_adjustment"]

    def _get_year_adjustments(
        self, year_adjustment_values: dict[str, dict[str, float]], time: Time
    ) -> dict[str, float]:
        """Retrieves the appropriate adjustment values based on the end year of the simulation."""
        end_year = time.end_year_int

        info_map = {"class": self.__class__.__name__, "function": self._get_year_adjustments.__name__}
        if not 2006 <= end_year <= 2016:
            bounded_end_year = min(2016, max(2006, end_year))
            self.om.add_log(
                f"Lactation curve adjustments not available for simulation ending in {end_year}",
                f"Using adjustments for {bounded_end_year}.",
                info_map,
            )
            end_year = bounded_end_year

        return year_adjustment_values[str(end_year)]

    def _get_region_adjustments(
        self, region_adjustment_values: dict[str, dict[str, float]], region_mapping: dict[str, str], fips_code: int
    ) -> dict[str, float]:
        """Retrieves the appropriate adjustment values for the region being simulated."""
        state_fips_code = int(fips_code / 1000)

        region = region_mapping[str(state_fips_code)]

        return region_adjustment_values[region]

    def _get_milking_frequency_adjustments(
        self, milking_frequency_adjustments: dict[str, dict[str, float]], milking_frequency: float
    ) -> dict[str, float]:
        """Retrieves the lactation curve adjustment values for the milking frequency of cows in the simulation."""
        if milking_frequency < MILKING_FREQUENCY_THRESHOLD:
            frequency = "twice_daily"
        else:
            frequency = "thrice_daily"

        return milking_frequency_adjustments[frequency]

    def _calculate_adjusted_wood_parameters(
        self,
        l_param: float,
        m_param: float,
        n_param: float,
        adjustments: list[dict[str, float]],
    ) -> dict[str, float]:
        """
        Computes Wood's Lactation Curve parameters adjusted for different factors.

        Parameters
        ----------
        l_param : float
            Base value for Wood's l parameter (unitless).
        m_param : float
            Base value for Wood's m parameter (unitless).
        n_param : float
            Base value for Wood's n parameter (unitless).
        adjustments : list[dict[str, float]]
            List of adjustment sets, where each dictionary in the list represents the adjustments for a single factor
            (region, parity, etc.) and contains the keys "l", "m", and "n".

        Returns
        -------
        dict[str, float]
            Dictionary containing the adjusted Wood l, m, and n parameters.

        """
        l_param += sum([adjustment["l"] for adjustment in adjustments])
        m_param += sum([adjustment["m"] for adjustment in adjustments]) * M_ADJUSTMENT_SCALING_FACTOR
        n_param += sum([adjustment["n"] for adjustment in adjustments]) * N_ADJUSTMENT_SCALING_FACTOR

        return {"l": l_param, "m": m_param, "n": n_param}

    def get_y_values_wood_curve(
        self, t: float, parameter_a: float, parameter_b: float, parameter_c: float
    ) -> np.float64:
        """
        Function that represents the milk yield at time t using parameters a, b,
        and c as the Wood's lactation curve parameters.

        Parameters
        ----------
        t : float
            Time.
        parameter_a: float
            Wood's lactation curve parameter a/l.
        parameter_b: float
            Wood's lactation curve parameter b/m.
        parameter_c: float
            Wood's lactation curve parameter c/n.

        Returns
        -------
        numpy.float64
            Milk yield at time t.

        References
        ----------
        Li, M., et al. "Investigating the effect of temporal, geographic, and management factors on US Holstein
        lactation curve parameters." Journal of Dairy Science 105.9 (2022): 7525-7538.

        """
        return parameter_a * np.power(t, parameter_b) * np.exp(-1 * parameter_c * t)

    def calc_integral_wood_curve(self, parameter_a: float, parameter_b: float, parameter_c: float) -> float:
        """
        Calculates the total milk yield from day 1 to day 305 of the lactation.

        Parameters
        ----------
        parameter_a: float
            Wood's lactation curve parameter a/l.
        parameter_b: float
            Wood's lactation curve parameter b/m.
        parameter_c: float
            Wood's lactation curve parameter c/n.

        Returns
        -------
        float
            Total milk yield from day 1 to day 305 of the lactation.

        """

        result, _ = quad(self.get_y_values_wood_curve, 1, 305, args=(parameter_a, parameter_b, parameter_c))
        return result

    def get_wood_parameters(
        self,
        lactation_group: str = None,
        year: str = None,
        month: str = None,
        region: str = None,
        milking_frequency: str = None,
        MY_305d: str | None = None,
    ) -> tuple[float, float, float]:
        """
        Adjusts the default lactation curve parameters based on farm-specific attributes.

        Parameters
        ----------
        lacation_group : str, default=None
            The lactation group or parity of the cows.
        year : str, default=None
            The simulation year. Minimum 2006, maximum 2016.
        month : str, default=None
            The simulation month.
        region : str, default=None
            The region of the simulated farm. One of 13 regions in United States as defined by Manfei's research.
        milking_frequency : str, default=None
            How often cows are milked per day. Can either be "2x/d" or "3x/d".
        MY_305d : str, default=None
            Annual 305-day milk yield in kilograms.

        Returns
        -------
        tuple
            Tuple of floats containing estimates for Wood's parameters l, m, n,
            and 305-day milk yield of the lactation group.
        """

        farm_specific = {}
        farm_specific["parity"] = lactation_group
        farm_specific["year"] = year
        farm_specific["month"] = month
        farm_specific["region"] = region
        farm_specific["milking_frequency"] = milking_frequency

        for category in ["parity", "year", "month", "region", "milking_frequency"]:
            if farm_specific[category]:
                adjustment_applied = False
                x = 0
                while (
                    x < len(self.adjustment_dict[category])
                    and (not adjustment_applied)
                    and (farm_specific[category] is not None)
                ):
                    if self.adjustment_dict[category][x][category] == farm_specific[category]:
                        l_param = self.wood_parameter_l + self.adjustment_dict[category][x]["adjustments"][0]
                        m_param = self.wood_parameter_m + self.adjustment_dict[category][x]["adjustments"][1] * 1e-2
                        n_param = self.wood_parameter_n + self.adjustment_dict[category][x]["adjustments"][2] * 1e-4
                        adjustment_applied = True

                    x = x + 1

        if MY_305d is None:
            MY_305d = self.calc_integral_wood_curve(l_param, m_param, n_param)
            return l_param, m_param, n_param, MY_305d

        else:
            min_diff = float("inf")
            l_param_best_estimate = 0
            MY_305d_best_estimate = 0
            MY_305d = float(MY_305d)

            for l_param_error in np.arange(-10, 10, 0.01):
                l_param_vary = l_param + l_param_error
                MY_305d_vary = self.calc_integral_wood_curve(l_param_vary, m_param, n_param)
                if abs(MY_305d_vary - MY_305d) < min_diff:
                    min_diff = abs(MY_305d_vary - MY_305d)
                    l_param_best_estimate = l_param_vary
                    MY_305d_best_estimate = MY_305d_vary
            return l_param_best_estimate, m_param, n_param, MY_305d_best_estimate

    def calc_parities(self) -> tuple[float, float, float]:
        """
        Calculates milk yield for each lactation group.

        Returns
        -------
        tuple
            List of floats. Floats represents the 305-day milk yield for lactation
            group/parity 1, lactation group/parity 2, and lactation group/parity 3, in that order.
        """
        # calculate lactation group yield

        if self.annual_MY_lbs is not None:
            total_avg_305 = self.annual_MY_lbs * 305 / (365 * self.num_milking_cows * 2.205)

            # Extracting percentage distribution for each lactation group
            percent_parity2 = self.parity_percentages[1] * 100
            percent_parity3 = self.parity_percentages[2] * 100

            # Solving for parity1_305 using the provided equation
            parity1_305 = (
                total_avg_305
                - percent_parity2 * self.parity2_MilkYield305_adj / 100
                - percent_parity3 * self.parity3_MilkYield305_adj / 100
            )

            # Calculating 305-day milk yield for each lactation group
            parity2_305 = parity1_305 + self.parity2_MilkYield305_adj
            parity3_305 = parity1_305 + self.parity3_MilkYield305_adj

        else:
            parity1_305 = None
            parity2_305 = None
            parity3_305 = None

        return parity1_305, parity2_305, parity3_305

    def set_lactation_curve_parameters(self) -> tuple[tuple, tuple, tuple]:
        """
        The wood lactation curve parameters for parities/lacation groups 1, 2, 3 of the herd.

        Returns
        -------
        tuple
            List of lists. Each list contains estimates for parameter l, m, n, and
            305-day milk yield for the lactation group. The list is ordered by lactation group.
        """
        parity1_305, parity2_305, parity3_305 = self.calc_parities()

        return (
            self.get_wood_parameters(
                lactation_group="1",
                year=self.year,
                region=self.region,
                milking_frequency=self.milking_freq,
                MY_305d=parity1_305,
            ),
            self.get_wood_parameters(
                lactation_group="2",
                year=self.year,
                region=self.region,
                milking_frequency=self.milking_freq,
                MY_305d=parity2_305,
            ),
            self.get_wood_parameters(
                lactation_group="3",
                year=self.year,
                region=self.region,
                milking_frequency=self.milking_freq,
                MY_305d=parity3_305,
            ),
        )
