---
title: "How to Configure Manure Management Components"
---
flowchart TD
    start[Start] --> checkPen{"Is there any unprocessed Pen \nin animal management?"}
    checkPen -->|No| Done[End]
    checkPen -->|Yes| createManureManagementPen[Create ManureManagementPen instance from the Pen]
    createManureManagementPen --> checkCustomBeddingConfig{"Is there any \n custom bedding config \n from user input?"}
    checkCustomBeddingConfig -- Yes --> getCustomBeddingConfig[Get custom bedding config for the Pen]
    checkCustomBeddingConfig -- No --> getDefaultBeddingConfig[Get default bedding config for the Pen]
    getCustomBeddingConfig --> setBeddingConfig[Set bedding config for the Pen]
    getDefaultBeddingConfig --> setBeddingConfig
    setBeddingConfig --> checkCustomHandlerConfig{"Is there any \n custom manure handler config \n from user input?"}
    checkCustomHandlerConfig -- Yes --> getCustomHandlerConfig[Get custom manure handler config for the Pen]
    checkCustomHandlerConfig -- No --> getDefaultHandlerConfig[Get default manure handler config for the Pen]
    getCustomHandlerConfig --> setHandlerConfig[Set handler config for the Pen]
    getDefaultHandlerConfig --> setHandlerConfig
    setHandlerConfig --> createSetReceptionPit[Create and set ReceptionPit for the Pen]
    createSetReceptionPit --> checkSeparator{"Is Manure Separator Required?"}
    checkSeparator -- Yes --> checkCustomSeparatorConfig{"Is there any \n custom separator config \n from user input?"}
    checkSeparator -- No --> setSeparatorNone[Set manure separator to None for the Pen]
    checkCustomSeparatorConfig -- Yes --> getCustomSeparatorConfig[Get custom separator config for the Pen]
    checkCustomSeparatorConfig -- No --> getDefaultSeparatorConfig[Get default separator config for the Pen]
    getCustomSeparatorConfig --> setSeparatorConfig[Set separator config for the Pen]
    getDefaultSeparatorConfig --> setSeparatorConfig
    setSeparatorConfig --> checkCustomTreatmentConfig{"Is there any \n custom treatment config \n from user input?"}
    setSeparatorNone --> checkCustomTreatmentConfig
    checkCustomTreatmentConfig -- Yes --> getCustomTreatmentConfig[Get custom treatment config for the Pen]
    checkCustomTreatmentConfig -- No --> getDefaultTreatmentConfig[Get default treatment config for the Pen]
    getCustomTreatmentConfig --> setTreatmentConfig[Set treatment config for the Pen]
    getDefaultTreatmentConfig --> setTreatmentConfig
    setTreatmentConfig --> checkPen