---
title: "How to Configure Manure Management Components"
---
flowchart TD
    start[Start] --> checkPen{"Is there any unprocessed Pen \nin animal management?"}
    checkPen --> |No| Done[End]
    checkPen --> |Yes| createManureManagementPen[Create ManureManagementPen instance from the Pen]
    createManureManagementPen --> checkConfig{"Is there any \n custom config \n for the component \n from user input?"}
    checkConfig -- Yes --> getCustomConfig[Get custom config for the component]
    checkConfig -- No --> getDefaultConfig[Get default config for the component]
    getCustomConfig --> setConfig[Set config for the component]
    getDefaultConfig --> setConfig
    setConfig --> checkNextComponent{Is there any next component?}
    checkNextComponent -- Yes --> checkConfig
    checkNextComponent -- No --> checkPen
