from dataclasses import dataclass, InitVar
from typing import List, Optional
from math import inf
from copy import deepcopy
from SC_redesign.Crop_and_Soil.soil.layer_data import LayerData

"""
This is a data class that stores and tracks all Soil attributes that are given in input files as well as ones that are
generated by modules in Soil
"""


@dataclass(kw_only=True)
class SoilData:
    # ID variables
    name: Optional[str] = "generic soil configuration"

    soil_layers: Optional[List[LayerData]] = None
    """list of soil layer data objects, top layer is 0th element, bottom is nth element"""

    field_size: InitVar[float] = None
    """Size of the field (ha)
        Note: this attribute is only used for initialization. After that it cannot be used.
    """

    # Track annual soil profile totals
    initial_water_content: float = None
    """Total soil water content at the beginning of a year, for use in determining annual change (mm)"""
    initial_nitrates_total: float = None
    """Total soil nitrate amounts at the beginning of a year, for use in determining annual change (kg per hectare)"""

    # Track annual hydrological activity
    annual_soil_evaporation_total: float = 0
    """Cumulative total of water evaporated from the soil this year (mm)"""
    annual_runoff_total: float = 0
    """Cumulative total of runoff that occurred in a year (mm)"""

    # Track annual erosion activity
    annual_eroded_sediment_total: float = 0
    """Cumulative total of sediment that eroded in a year (metric tons)"""
    annual_surface_runoff_total: float = 0
    """Cumulative total of volume of surface runoff that occurred in a year (mm per hectare)"""

    # Track annual phosphorus activity
    annual_runoff_fertilizer_phosphorus: float = 0
    """Cumulative total of phosphorus from surface-applied fertilizer that was carried off the field by runoff (kg)"""
    annual_runoff_machine_manure_inorganic_phosphorus: float = 0
    """Cumulative total of inorganic phosphorus from machine-applied manure that was carried off the field by runoff
        (kg)"""
    annual_runoff_machine_manure_organic_phosphorus: float = 0
    """Cumulative total of organic phosphorus from machine-applied manure that was carried off the field by runoff
        (kg)"""
    annual_runoff_grazing_manure_inorganic_phosphorus: float = 0
    """Cumulative total of inorganic phosphorus from grazer-applied manure that was carried off the field by runoff
        (kg)"""
    annual_runoff_grazing_manure_organic_phosphorus: float = 0
    """Cumulative total of organic phosphorus from grazer-applied manure that was carried off the field by runoff
        (kg)"""
    annual_soil_phosphorus_runoff: float = 0
    """Cumulative total of phosphorus that was from the top layer of the soil profile by runoff (kg)"""

    # Track annual nitrogen loss from field
    annual_runoff_nitrates_total: float = 0
    """Cumulative total of nitrates that were removed from the top soil layer by runoff (kg)"""
    annual_runoff_ammonium_total: float = 0
    """Cumulative total of ammonium that was removed from the top soil layer by runoff (kg)"""
    annual_eroded_fresh_organic_nitrogen_total: float = 0
    """Cumulative total of fresh organic nitrogen that was removed from the top soil layer by erosion (kg)"""
    annual_eroded_stable_organic_nitrogen_total: float = 0
    """Cumulative total of stable organic nitrogen that was removed from the top soil layer by erosion (kg)"""
    annual_eroded_active_organic_nitrogen_total: float = 0
    """Cumulative total of active organic nitrogen that was removed from the top soil layer by erosion (kg)"""

    # ---- evaporation
    water_evaporated: float = 0
    """Amount of water evaporated from the soil profile on the current day (mm)"""

    # ---- infiltration
    second_moisture_condition_parameter: float = 85
    """'curve number' parameter for average moisture conditions equation (unitless)"""
    previous_retention_parameter: Optional[float] = None
    """retention parameter for the previous day (mm) (used in SWAT 2:1.1.9)"""
    average_subbasin_slope: float = 0.05
    """average slope of the subbasin expressed as rise over run (meters / meters)"""
    moisture_condition_parameter: Optional[float] = None
    """curve number value adjusted for moisture content (unitless) (SWAT 2:1.1.11)"""
    accumulated_runoff: Optional[float] = None
    """the amount of rainfall discharged as runoff during the day (mm)"""

    # ---- percolation
    vadose_zone_layer: Optional[LayerData] = None
    """LayerData object that represents the vadose zone layer, top depth is set equal bottom depth of lowest soil layer
        and bottom depth is arbitrary, starts with no water"""
    time_step: float = 24
    """length of time step over which percolation occurs (hours) """

    # ---- temperature
    albedo: float = 0.16
    """proportion of solar radiation that is reflected by the soil surface (unitless)"""
    previous_temperature_effect: float = 0.8
    """variable that controls the influence of previous day's temperature on current day's temperature, range is from 0
    to 1, inclusive. SWAT sets the lag coefficient to 0.8 (paragraph between equations 1:1.3.3, 4) (unitless)
    """

    # ---- Erosion
    slope_length: float = 3
    """length of the slope (meters)"""
    manning: float = 0.4
    """the Manning roughness coefficient for this subbasin (unitless)"""
    snow_cover_water_content: float = 0
    """water content of the snow cover (mm)"""
    eroded_sediment: float = 0
    """cumulative amount of sediment that has been eroded off of the field in a day (metric tons)"""
    surface_runoff_volume: Optional[float] = None
    """volume of surface runoff (mm per hectare), used in SWAT equation 4:1.1.1."""

    # ---- decomposition
    decomposition_temperature_effect: Optional[float] = None
    """temperature effect on decomposition factor (unitless) (pseudocode_soil S.6.A.1)"""

    # ---- Fertilizer (Phosphorus Cycling)
    cover_type: str = "BARE"
    """The cover type of the soil surface, can be bare, residue covered, or grassed"""
    full_available_phosphorus_pool: float = 0
    """Starting value of the available phosphorus pool (kg). This value does not change when phosphorus is removed from
        the available phosphorus pool, but does change when a new application of fertilizer phosphorus is applied.
    """
    available_phosphorus_pool: float = 0
    """Amount of phosphorus available for soil adsorption and leaching via runoff before the first rainfall event after
        application (kg)
    """
    recalcitrant_phosphorus_pool: float = 0
    """Amount of phosphorus available for soil adsorption and leaching via runoff after the first rainfall event (kg)"""
    runoff_phosphorus_pool: float = 0
    """Amount of solubilized phosphorus that has been leached off the field by runoff (kg)"""
    days_since_application: int = 0
    """Number of days since phosphorus was applied to field via fertilizer"""
    rain_events_after_fertilizer_application: int = 0
    """Number of rain events that have occurred since phosphorus was applied to field via fertilizer"""

    # ---- Manure (Phosphorus Cycling)
    machine_manure_dry_mass: float = 0
    """The dry weight equivalent of manure mass on the field that was applied by machine (kg)"""
    machine_manure_applied_mass: float = 0
    """The dry weight equivalent of the most recent application of manure applied by machine (kg)"""
    machine_manure_field_coverage: float = 0
    """Fraction of the field that is covered by machine-applied manure, between [0, 1] (unitless)"""
    machine_manure_moisture_factor: float = 0
    """Fraction representing the current moisture level of the machine-applied manure on the field, between [0, 0.9]
        (unitless)
    """
    machine_water_extractable_inorganic_phosphorus: float = 0
    """Amount of water extractable inorganic phosphorus on the field that was applied by machine (kg)"""
    machine_water_extractable_organic_phosphorus: float = 0
    """Amount of water extractable organic phosphorus on the field that was applied by machine (kg)"""
    machine_stable_inorganic_phosphorus: float = 0
    """Amount of stable inorganic phosphorus on the field that was applied by machine (kg)"""
    machine_stable_organic_phosphorus: float = 0
    """Amount of stable organic phosphorus on the field that was applied by machine (kg)"""

    grazing_manure_dry_mass: float = 0
    """The dry weight equivalent of manure mass on the field that was applied by grazers (kg)"""
    grazing_manure_applied_mass: float = 0
    """The dry weight equivalent of the most recent application of manure applied by grazers (kg)"""
    grazing_manure_field_coverage: float = 0
    """Fraction of the field that is covered by grazing-applied manure, between [0, 1] (unitless)"""
    grazing_manure_moisture_factor: float = 0
    """Fraction representing the current moisture level of the grazing-applied manure on the field, between [0, 0.9]
        (unitless)
    """
    grazing_water_extractable_inorganic_phosphorus: float = 0
    """Amount of water extractable inorganic phosphorus on the field that was applied by grazing (kg)"""
    grazing_water_extractable_organic_phosphorus: float = 0
    """Amount of water extractable organic phosphorus on the field that was applied by grazing (kg)"""
    grazing_stable_inorganic_phosphorus: float = 0
    """Amount of stable inorganic phosphorus on the field that was applied by grazing (kg)"""
    grazing_stable_organic_phosphorus: float = 0
    """Amount of stable organic phosphorus on the field that was applied by grazing (kg)"""

    # ---- Residue partition (Carbon Cycling)
    plant_surface_residue = 0
    """plant residue on the surface of the soil (kg/ha)"""
    plant_root_residue = 0
    """plant residue below the surface of the soil (kg/ha)"""
    plant_residue_lignin_composition: float = 0
    """lignin fraction of plant residue (unitless)"""
    plant_lignin_nitrogen_ratio: float = 0
    """plant lignin to nitrogen ratio (unitless)"""
    plant_residue_metabolic_fraction: float = 0
    """plant residue fraction that is metabolic (unitless)"""
    total_residue: float = 0
    """total amount of soil residue ever added to the field"""  # TODO: needed?
    @property
    def all_residue(self) -> float:  # TODO: not currently used.
        """amount of total plant residue, above and below-ground, on the field (kg/ha)"""
        return self.plant_surface_residue + self.plant_root_residue

    def __post_init__(self, field_size: float):
        """This method initializes attributes that either cannot be set to a default above or depend on other
            attributes in the object to be set before they can be set

        Parameters
        ----------
        field_size: float
            Size of the field (ha)

        Raises
        ------
        TypeError
            If the field size is None (meaning it likely was not included when the SoilData() object was initialized).
        ValueError
            If the field size specified is not greater than 0.
        ValueError
            If the bottom depth of the top layer of soil is < 20.

        Notes
        -----
        The SoilData class itself does not need the field size, but it requires it if the soil layers are not defined
        for it.

        """
        if field_size is None:
            raise TypeError("'field_size' attribute is NoneType, must be given value when SoilData is initialized.")
        elif field_size <= 0:
            raise ValueError(f"Expected field_size to be greater than 0, received {field_size}.")

        if self.soil_layers is None:
            self.soil_layers = [LayerData(top_depth=0, bottom_depth=20, field_size=field_size,
                                          residue=self.plant_surface_residue),
                                LayerData(top_depth=20, bottom_depth=50, field_size=field_size),
                                LayerData(top_depth=50, bottom_depth=80, field_size=field_size),
                                LayerData(top_depth=80, bottom_depth=200, field_size=field_size)]
        elif self.soil_layers[0].bottom_depth < 20:
            raise ValueError(f"Expected bottom depth of top soil layer must be 20 mm or greater, received "
                             f"'{self.soil_layers[0].bottom_depth}'.")
        elif self.soil_layers[0].bottom_depth > 20:
            self._subdivide_top_layer(field_size)

        if self.vadose_zone_layer is None:
            # configures the vadose zone LayerData object based on where the soil profile ends
            self.vadose_zone_layer = LayerData(top_depth=self.soil_layers[-1].bottom_depth,
                                               bottom_depth=10000000,  # bottom depth is 10,000 meters by default
                                               soil_water_concentration=0,
                                               saturation_point_water_concentration=inf,
                                               initial_labile_inorganic_phosphorus_concentration=0,
                                               initial_soil_nitrate_concentration=0,
                                               field_size=field_size)
            self.vadose_zone_layer.active_organic_nitrogen_content = 0
            self.vadose_zone_layer.stable_organic_nitrogen_content = 0

        # Set the initial water content for the first year of the simulation
        self.initial_water_content = self.profile_soil_water_content
        self.initial_nitrates_total = self.profile_nitrates_total

    def _subdivide_top_layer(self, field_size: float) -> None:
        """This method ensures that the soil profile has a top layer that is 20 mm deep.

        Parameters
        ----------
        field_size : float
            Size of the field (ha)

        Notes
        -----
        The presence of a top layer of soil that is 20 mm deep is a necessity to properly execute SurPhos. This top 20
        mm of soil is where most of the phosphorus that is applied stays in the soil profile, and keeping it in the top
        20 mm of soil makes it more available to be eroded off the field by runoff.

        This method assumes that the top layer of soil defined by the user is greater than 20 mm thick.

        """
        new_top_layer = deepcopy(self.soil_layers[0])
        new_top_layer.bottom_depth = 20
        new_top_layer.__post_init__(field_size, self.plant_surface_residue)
        self.soil_layers[0].top_depth = 20
        self.soil_layers[0].__post_init__(field_size, 0)
        self.soil_layers.insert(0, new_top_layer)

    def get_vectorized_layer_attribute(self, attribute: str) -> List[any]:
        """returns a list containing the specified attribute for each soil layer

        Parameters
        ----------
        attribute : str
            the LayerData attribute or property to be vectorized

        Returns
        -------
        layered_attribute : list[any]
            values of the specified attribute for each layer
        """
        return [getattr(layer, attribute) for layer in self.soil_layers]

    def set_vectorized_layer_attribute(self, attribute: str, values: List[any]) -> None:
        """sets a given attribute for all layers in soil_data

        Parameters
        ----------
        attribute : str
            the LayerData attribute to set
        values : list[any]
            values of the attribute to set for each layer
        """
        [setattr(layer, attribute, val) for layer, val in zip(self.soil_layers, values)]

    def do_annual_reset(self) -> None:
        """This method resets all annual totals to zero at the end of the year/beginning of a new year"""
        # Reset soil profile totals
        self.initial_water_content = self.profile_soil_water_content
        self.initial_nitrates_total = self.profile_nitrates_total

        # Reset hydrological activity totals
        self.annual_soil_evaporation_total = 0
        self.annual_runoff_total = 0

        # Reset erosion activity totals
        self.annual_eroded_sediment_total = 0
        self.annual_surface_runoff_total = 0

        # Reset phosphorus totals
        self.annual_runoff_fertilizer_phosphorus = 0
        self.annual_runoff_machine_manure_organic_phosphorus = 0
        self.annual_runoff_machine_manure_inorganic_phosphorus = 0
        self.annual_runoff_grazing_manure_organic_phosphorus = 0
        self.annual_runoff_grazing_manure_inorganic_phosphorus = 0

        self.annual_soil_phosphorus_runoff = 0

        self.annual_runoff_nitrates_total = 0
        self.annual_runoff_ammonium_total = 0
        self.annual_eroded_fresh_organic_nitrogen_total = 0
        self.annual_eroded_stable_organic_nitrogen_total = 0
        self.annual_eroded_active_organic_nitrogen_total = 0

        # Reset carbon cycle
        for layer in self.soil_layers:
            layer.do_annual_reset()

    @property
    def profile_soil_water_content(self) -> float:
        """
        Returns: amount of water in the entire soil profile (excluding the amount of water held in the profile at the
            wilting point) (mm)
        Details: this method for calculating total soil water content assumes the lower bound of water to be 0. It also
            calculates the soil water content per layer, meaning that if one layer has water content greater than its
            wilting water point and another layer has water content less than its wilting point, the first layer will
            not have to compensate for the deficit in the second layer.
        """
        if self.soil_layers is None:
            return 0
        else:
            water_sum = 0
            for layer in self.soil_layers:
                water_sum += max(0.0, (layer.water_content - layer.wilting_point_content))
            return water_sum

    @property
    def profile_saturation(self) -> float:
        """
        Returns: amount of water in the soil profile when completely saturated (mm)
        """
        if self.soil_layers is None:
            return 0
        else:
            saturation_sum = 0
            for layer in self.soil_layers:
                saturation_sum += layer.saturation_content
            return saturation_sum

    @property
    def profile_field_capacity(self) -> float:
        """
         Returns: total amount of water contained in the entire soil profile at field capacity (but not saturated) (mm)
        """
        if self.soil_layers is None:
            return 0
        else:
            field_capacity_sum = 0
            for layer in self.soil_layers:
                field_capacity_sum += layer.field_capacity_content
            return field_capacity_sum

    @property
    def soil_water_factor(self) -> float:
        """Returns: the soil water factor (unitless)
        SWAT Reference: 5:2.3.18
        """
        return self.profile_soil_water_content / (0.85 * self.profile_field_capacity)

    # TODO: implement method that validates all the values inside the SoilData object, including
    #   - soil layers all have top depths above bottom depths, top depth of top layer is 0, none of the layers are
    #       overlapping, etc.
    #   - soil evaporation adjusted is always less than or equal to maximum soil evaporation
    #   - potential evapotranspiration adjusted is always less than or equal to maximum evapotranspiration
    #   - average slope fraction is always in the range 0 to 1 inclusive (I think)

    @property
    def profile_bulk_density(self) -> float:
        """Average bulk density of the soil profile based on the bulk density of each soil layer, weighted by the
            thickness (Mg per cubic meter)"""
        weighted_densities_sum = 0
        weights_sum = 0
        for layer in self.soil_layers:
            weighted_densities_sum += (layer.layer_thickness * layer.bulk_density)
            weights_sum += layer.layer_thickness
        return weighted_densities_sum / weights_sum

    @property
    def profile_nitrates_total(self) -> float:
        """Calculates and returns the total amount of nitrates in the soil (kg per hectare)"""
        if self.soil_layers is None:
            return 0
        else:
            nitrates_sum = 0
            for layer in self.soil_layers:
                nitrates_sum += layer.nitrate_content
            return nitrates_sum

    @property
    def cover_factor(self) -> float:
        """Returns the cover factor based on the cover type, for use in determining how much phosphorus is absorbed by
            the soil from surface applied fertilizer before the first rainfall event after application (unitless).
        Raises:
            ValueError: If cover type is not one of the three acceptable types ("BARE", "RESIDUE_COVER", or "GRASSED")
        References:
            pseudocode_soil [S.5.C.I.1], SurPhos [14] (Note: constants differ between these documents, defer to
            pseudocode_soil and old code)
        """
        if self.cover_type == "BARE":
            return 0.5333
        elif self.cover_type == "RESIDUE_COVER":
            return 0.6667
        elif self.cover_type == "GRASSED":
            return 0.8
        raise ValueError(f"Expected cover type to be \'BARE\', \'RESIDUE_COVER\', or \'GRASSED\', "
                         f"received: '{self.cover_type}'.")

    @property
    def solubilizing_factor(self) -> float:
        """Returns the fraction of fertilizer phosphorus that is removed from the available fertilizer phosphorus pool
            (when number of rain events is less than or equal to 1) or the recalcitrant fertilizer phosphorus pool
            (when number of rain events is greater than or equal to 2) (unitless).
            References:
                SurPhos paragraph just below [16]
        """
        if self.rain_events_after_fertilizer_application <= 1:
            return 1
        elif self.rain_events_after_fertilizer_application == 2:
            return 0.40
        else:
            return 0.075
