from dataclasses import dataclass
from typing import List, Optional
from math import inf
from SC_redesign.Crop_and_Soil.soil.layer_data import LayerData

"""
This is a data class that stores and tracks all Soil attributes that are given in input files as well as ones that are 
generated by modules in Soil
"""


@dataclass
class SoilData:
    soil_layers: Optional[List[LayerData]] = None
    """list of soil layer data objects, top layer is 0th element, bottom is nth element"""

    # ---- evapotranspiration
    potential_evapotranspiration: Optional[float] = None
    """potential evapotranspiration for a given day (mm per day)"""
    potential_evapotranspiration_adjusted: Optional[float] = None
    """amount of evapotranspiration adjusted for water in canopy (mm)
        SWAT Reference: 2:2.3.1"""
    transpiration: float = 30  # arbitrary
    """amount of transpiration on a given day (mm)"""
    soil_evaporation_adjusted: Optional[float] = None
    """maximum amount of evaporation from soil on a given day adjusted for plant use (mm)"""
    maximum_soil_evaporation: Optional[float] = None
    """maximum amount of evaporation from soil on a given day (mm)"""

    # ---- infiltration
    previous_retention_parameter: Optional[float] = None
    """retention parameter for the previous day (mm) (used in SWAT 2:1.1.9)"""
    average_slope_fraction: float = 0.05
    """average slope fraction of the subbasin"""
    moisture_condition_parameter: Optional[float] = None
    """curve number value adjusted for moisture content (unitless) (SWAT 2:1.1.11)"""

    # ---- percolation
    vadose_zone_layer: Optional[LayerData] = None
    """Datalayer object that represents the vadose zone, arbitrary top and bottom depths, starts with no water"""
    time_step: float = 24
    """length of time step over which percolation occurs (hours) """

    # ---- temperature
    albedo: float = 0.16
    """ratio of reflected to solar radiation (unitless)"""
    # TODO: check above definition with a SME because all I did to get it was google 'soil albedo'
    lag_coefficient: float = 0.8
    """variable that controls the influence of previous day's temperature on current day's temperature, range is from 0
    to 1, inclusive. SWAT sets the lag coefficient to 0.8 (paragraph between equations 1:1.3.3, 4) (unitless)
    """

    @property
    def profile_soil_water_content(self) -> float:
        """

        Returns: amount of water in the entire soil profile (excluding the amount of water held in the profile at the
            wilting point) in mm

        Details: this method for calculating total soil water content assumes the lower bound of water to be 0. It also
            calculates the soil water content per layer, meaning that if one layer has water content greater than its
            wilting water point and another layer has water content less than its wilting point, the first layer will
            not have to compensate for the deficit in the second layer.

        """
        if self.soil_layers is None:
            return 0
        else:
            water_sum = 0
            for layer in self.soil_layers:
                water_sum += max(0, (layer.soil_water_content - layer.wilting_point_content))
            return

    @property
    def profile_saturation(self) -> float:
        """

        Returns: amount of water in the soil profile when completely saturated in mm

        """
        if self.soil_layers is None:
            return 0
        else:
            saturation_sum = 0
            for layer in self.soil_layers:
                saturation_sum += layer.saturation_content
            return saturation_sum

    @property
    def profile_field_capacity(self) -> float:
        """

        Returns: total amount of water contained in the soil profile at field capacity (but not saturated) in mm

        """
        if self.soil_layers is None:
            return 0
        else:
            field_capacity_sum = 0
            for layer in self.soil_layers:
                field_capacity_sum += layer.field_capacity_content
            return field_capacity_sum

    @property
    def soil_water_factor(self):
        """

        Returns: the soil water factor (unitless)

        SWAT Reference: 5:2.3.18
        """
        return self.profile_soil_water_content / (0.85 * self.profile_field_capacity)

    # TODO: implement method that validates all the values inside the SoilData object, including
    #   - soil layers all have top depths above bottom depths, top depth of top layer is 0, none of the layers are
    #       overlapping, etc.
    #   - soil evaporation adjusted is always less than or equal to maximum soil evaporation
    #   - potential evapotranspiration adjusted is always less than or equal to maximum evapotranspiration
    #   - average slope fraction is always in the range 0 to 1 inclusive (I think)

    @property
    def profile_bulk_density(self):
        """

        Returns: average bulk density of the soil profile based on the bulk density of each soil layer and weighted by
            the thickness of that layer

        """
        weighted_densities_sum = 0
        weights_sum = 0
        for layer in self.soil_layers:
            weighted_densities_sum += (layer.layer_thickness * layer.bulk_density)
            weights_sum += layer.layer_thickness
        return weighted_densities_sum / weights_sum
