from dataclasses import dataclass
from typing import List, Optional
from math import inf
from SC_redesign.Crop_and_Soil.soil.layer_data import LayerData

"""
This is a data class that stores and tracks all Soil attributes that are given in input files as well as ones that are 
generated by modules in Soil
"""


@dataclass(kw_only=True)
class SoilData:
    # ID variables
    name: Optional[str] = "generic soil configuration"

    soil_layers: Optional[List[LayerData]] = None
    """list of soil layer data objects, top layer is 0th element, bottom is nth element"""

    # Track annual soil profile totals
    initial_water_content: float = None
    """Total soil water content at the beginning of a year, for use in determining annual change (mm)"""
    initial_nitrates_total: float = None
    """Total soil nitrate amounts at the beginning of a year, for use in determining annual change (kg per hectare)"""

    # Track annual hydrological activity
    annual_potential_evapotranspiration_total: float = 0
    """Cumulative total of potential evapotranspiration that occurred in a year (mm)"""
    annual_adjusted_potential_evapotranspiration_total: float = 0
    """Cumulative total of adjusted potential evapotranspiration that occurred in a year (mm)"""
    annual_maximum_soil_evaporation_total: float = 0
    """Cumulative total of maximum soil evaporation that occurred in a year (mm)"""
    annual_adjusted_soil_evaporation_total: float = 0
    """Cumulative total of adjusted soil evaporation that occurred in a year (mm)"""
    annual_runoff_total: float = 0
    """Cumulative total of runoff that occurred in a year (mm)"""

    # Track annual erosion activity
    annual_eroded_sediment_total: float = 0
    """Cumulative total of sediment that eroded in a year (metric tons)"""
    annual_surface_runoff_total: float = 0
    """Cumulative total of volume of surface runoff that occurred in a year (mm per hectare)"""

    # ---- evapotranspiration
    potential_evapotranspiration: Optional[float] = None
    """potential evapotranspiration for a given day (mm per day)"""
    potential_evapotranspiration_adjusted: Optional[float] = None
    """amount of evapotranspiration adjusted for water in canopy (mm)
        SWAT Reference: 2:2.3.1"""
    transpiration: float = 30  # arbitrary
    """amount of transpiration on a given day (mm)"""
    soil_evaporation_adjusted: Optional[float] = None
    """maximum amount of evaporation from soil on a given day adjusted for plant use (mm)"""
    maximum_soil_evaporation: Optional[float] = None
    """maximum amount of evaporation from soil on a given day (mm)"""

    # ---- infiltration
    second_moisture_condition_parameter: float = 85
    """curve number for average moisture conditions (unitless)"""
    previous_retention_parameter: Optional[float] = None
    """retention parameter for the previous day (mm) (used in SWAT 2:1.1.9)"""
    average_subbasin_slope: float = 0.05
    """average slope of the subbasin expressed as rise over run (meters / meters)"""
    moisture_condition_parameter: Optional[float] = None
    """curve number value adjusted for moisture content (unitless) (SWAT 2:1.1.11)"""
    accumulated_runoff: Optional[float] = None
    """accumulated runoff or rainfall excess (mm)"""

    # ---- percolation
    vadose_zone_layer: Optional[LayerData] = None
    """LayerData object that represents the vadose zone layer, top depth is set equal bottom depth of lowest soil layer 
        and bottom depth is arbitrary, starts with no water"""
    time_step: float = 24
    """length of time step over which percolation occurs (hours) """

    # ---- temperature
    albedo: float = 0.16
    """proportion of solar radiation that is reflected by the soil surface (unitless)"""
    previous_temperature_effect: float = 0.8
    """variable that controls the influence of previous day's temperature on current day's temperature, range is from 0
    to 1, inclusive. SWAT sets the lag coefficient to 0.8 (paragraph between equations 1:1.3.3, 4) (unitless)
    """

    # ---- Erosion
    slope_length: float = 3
    """length of the slope (meters)"""
    manning: float = 0.4
    """the Manning roughness coefficient for this subbasin (unitless)"""
    peak_runoff_rate: Optional[float] = None
    """the peak runoff rate (meters cubed per second)"""
    snow_cover_water_content: float = 0
    """water content of the snow cover (mm)"""
    eroded_sediment: float = 0
    """cumulative amount of sediment that has been eroded off of the field in a day (metric tons)"""
    surface_runoff_volume: Optional[float] = None
    """volume of surface runoff (mm per hectare), used in SWAT equation 4:1.1.1."""

    def __post_init__(self):
        """This method initializes attributes that either cannot be set to a default above or depend on need other
            attributes in the object to be set before they can be set"""
        if self.soil_layers is None:
            # sets the soil layers to a default set if user does not provide any
            self.soil_layers = [LayerData(top_depth=0, bottom_depth=50, nitrate=0.5),
                                LayerData(top_depth=50, bottom_depth=80, nitrate=1),
                                LayerData(top_depth=80, bottom_depth=200, nitrate=5)]

        if self.vadose_zone_layer is None:
            # configures the vadose zone LayerData object based on where the soil profile ends
            self.vadose_zone_layer = LayerData(top_depth=self.soil_layers[-1].bottom_depth,
                                               bottom_depth=10000000,  # bottom depth is 10,000 meters by default
                                               soil_water_concentration=0,
                                               saturation_point_water_concentration=inf)

        # Set the initial water content for the first year of the simulation
        self.initial_water_content = self.profile_soil_water_content
        self.initial_nitrates_total = self.profile_nitrates_total

    def annual_reset(self) -> None:
        """This method resets all annual totals to zero at the end of the year/beginning of a new year"""
        # Reset soil profile totals
        self.initial_water_content = self.profile_soil_water_content
        self.initial_nitrates_total = self.profile_nitrates_total

        # Reset hydrological activity totals
        self.annual_potential_evapotranspiration_total = 0
        self.annual_adjusted_potential_evapotranspiration_total = 0
        self.annual_maximum_soil_evaporation_total = 0
        self.annual_adjusted_soil_evaporation_total = 0
        self.annual_runoff_total = 0

        # Reset erosion activity totals
        self.annual_eroded_sediment_total = 0
        self.annual_surface_runoff_total = 0

    @property
    def profile_soil_water_content(self) -> float:
        """

        Returns: amount of water in the entire soil profile (excluding the amount of water held in the profile at the
            wilting point) (mm)

        Details: this method for calculating total soil water content assumes the lower bound of water to be 0. It also
            calculates the soil water content per layer, meaning that if one layer has water content greater than its
            wilting water point and another layer has water content less than its wilting point, the first layer will
            not have to compensate for the deficit in the second layer.

        """
        if self.soil_layers is None:
            return 0
        else:
            water_sum = 0
            for layer in self.soil_layers:
                water_sum += max(0, (layer.water_content - layer.wilting_point_content))
            return water_sum

    @property
    def profile_saturation(self) -> float:
        """
        Returns: amount of water in the soil profile when completely saturated (mm)
        """
        if self.soil_layers is None:
            return 0
        else:
            saturation_sum = 0
            for layer in self.soil_layers:
                saturation_sum += layer.saturation_content
            return saturation_sum

    @property
    def profile_field_capacity(self) -> float:
        """
         Returns: total amount of water contained in the entire soil profile at field capacity (but not saturated) (mm)
        """
        if self.soil_layers is None:
            return 0
        else:
            field_capacity_sum = 0
            for layer in self.soil_layers:
                field_capacity_sum += layer.field_capacity_content
            return field_capacity_sum

    @property
    def soil_water_factor(self) -> float:
        """Returns: the soil water factor (unitless)

        SWAT Reference: 5:2.3.18
        """
        return self.profile_soil_water_content / (0.85 * self.profile_field_capacity)

    # TODO: implement method that validates all the values inside the SoilData object, including
    #   - soil layers all have top depths above bottom depths, top depth of top layer is 0, none of the layers are
    #       overlapping, etc.
    #   - soil evaporation adjusted is always less than or equal to maximum soil evaporation
    #   - potential evapotranspiration adjusted is always less than or equal to maximum evapotranspiration
    #   - average slope fraction is always in the range 0 to 1 inclusive (I think)

    @property
    def profile_bulk_density(self) -> float:
        """Average bulk density of the soil profile based on the bulk density of each soil layer, weighted by the
            thickness (Mg per cubic meter)"""
        weighted_densities_sum = 0
        weights_sum = 0
        for layer in self.soil_layers:
            weighted_densities_sum += (layer.layer_thickness * layer.bulk_density)
            weights_sum += layer.layer_thickness
        return weighted_densities_sum / weights_sum

    @property
    def profile_nitrates_total(self) -> float:
        """Calculates and returns the total amount of nitrates in the soil (kg per hectare)"""
        if self.soil_layers is None:
            return 0
        else:
            nitrates_sum = 0
            for layer in self.soil_layers:
                nitrates_sum += layer.nitrate
            return nitrates_sum
