from __future__ import annotations

from typing import List
from typing import Optional

from RUFAS.routines.manure.manure_handlers.manure_handler_daily_output import ManureHandlerDailyOutput
from RUFAS.routines.manure.reception_pits.reception_pit_daily_output import ReceptionPitDailyOutput


class ReceptionPit:
    """Class for a reception pit.

    Attributes:
        all_output: List of all daily outputs.

    """

    def __init__(self):
        """Initialize a ReceptionPit object."""
        self.all_output: List[ReceptionPitDailyOutput] = []

    @property
    def last_output(self) -> Optional[ReceptionPitDailyOutput]:
        """Return the last daily output data generated by the last daily_update() call."""
        return self.all_output[-1] if len(self.all_output) > 0 else None

    def daily_update(self, manure_handler_daily_output: ManureHandlerDailyOutput) -> ReceptionPitDailyOutput:
        """Calculate and store the daily output of the reception pit.

        Args:
            manure_handler_daily_output: The daily output of a manure handler.

        Returns:
            The daily output of the reception pit.

        """
        daily_output = ReceptionPitDailyOutput.get_instance(manure_handler_daily_output)
        self.all_output.append(daily_output)
        return daily_output
