class Units:
    """Units for quantities in manure management output objects."""

    manure_urea = 'g_per_L'
    manure_urine = 'kg'
    manure_urine_ammoniacal_nitrogen = 'kg'
    manure_total_ammoniacal_nitrogen = 'kg'
    liquid_manure_total_ammoniacal_nitrogen = 'kg'
    manure_nitrogen = 'kg'
    liquid_manure_nitrogen = 'kg'
    manure_mass = 'kg'
    manure_total_solids = 'kg'
    liquid_manure_total_solids = 'kg'
    manure_degradable_volatile_solids = 'kg'
    manure_non_degradable_volatile_solids = 'kg'
    liquid_manure_total_volatile_solids = 'kg'
    manure_phosphorus = 'kg'
    liquid_manure_phosphorus = 'kg'
    manure_potassium = 'kg'
    liquid_manure_potassium = 'kg'

    manure_methane = 'kg'
    housing_methane = 'kg'
    storage_methane = 'kg'
    housing_carbon_dioxide = 'kg'
    housing_ammonia = 'kg'
    storage_ammonia = 'kg'
    temperature = 'C'

    manure_volume = 'm^3'
    cleaning_water_volume = 'm^3'
    total_bedding_volume = 'm^3'
    total_water_volume_in_milking_center = 'm^3'
    total_daily_manure_volume = 'm^3'
    liquid_manure_daily_volume = 'm^3'

    # Specific to manure separator output
    final_solids_wet_mass = 'kg'
    final_solids_wet_mass_volume = 'm^3'
    solid_manure_total_solids = 'kg'
    solid_manure_total_volatile_solids = 'kg'
    solid_manure_nitrogen = 'kg'
    solid_manure_phosphorus = 'kg'
    solid_manure_potassium = 'kg'

    final_daily_volume = 'm^3'
    final_manure_volume = 'm^3'

    sludge_manure_total_solids = 'kg'
    sludge_manure_total_volatile_solids = 'kg'
    sludge_manure_nitrogen = 'kg'
    sludge_manure_phosphorus = 'kg'
    sludge_manure_potassium = 'kg'
    sludge_manure_daily_volume = 'm^3'
    accumulated_sludge_volume = 'm^3'
    accumulated_final_manure_volume = 'm^3'
