name: Format, Lint, Test, Coverage, and Type Checking

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  format_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Get all added or modified files
        run: |
          BASE_BRANCH=${{ github.base_ref }} || "main"
          git fetch origin $BASE_BRANCH
          if ! git rev-parse --verify --quiet origin/$BASE_BRANCH; then
            echo "Fallback to main branch because $BASE_BRANCH does not exist."
            BASE_BRANCH="main"
            git fetch origin $BASE_BRANCH
          fi
          ALL_CHANGED_FILES=$(git diff --name-only origin/$BASE_BRANCH HEAD)
          echo "All Changed Files: $ALL_CHANGED_FILES"

          FILES=$(echo "$ALL_CHANGED_FILES" | grep '\.py$' | tr '\n' ' ')
          echo "FILES=$FILES" >> $GITHUB_ENV

          OTHER_FILES=$(echo "$ALL_CHANGED_FILES" | grep -v '\.py$' | tr '\n' ' ')
          echo "OTHER_FILES=$OTHER_FILES" >> $GITHUB_ENV

      - name: Check for Unauthorized Changes
        run: |
          paths_to_protect=(
            "input/data/tasks/default_task.json"
          )
          unauthorized_changes=false
          unauthorized_paths=""
          
          # Check if any of the protected paths have been changed
          for path in "${paths_to_protect[@]}"; do
            if echo "${FILES} ${OTHER_FILES}" | grep -q "$path"; then
              unauthorized_changes=true
              unauthorized_paths+="$path, "
            fi
          done
          
          if $unauthorized_changes; then
            echo "Unauthorized changes detected in protected files: ${unauthorized_paths%, }"
            echo "Review and remove these changes if they are not intended."
            exit 1
          else
            echo "No unauthorized changes detected."
          fi

      - name: Format code with Black and commit changes
        if: ${{ env.FILES != '' && github.ref != 'refs/heads/main' }}
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref }}
        run: |
          black ${{ env.FILES }}
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Apply Black Formatting" --allow-empty
          git remote set-url origin https://${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          CLEAN_BRANCH_NAME=${BRANCH_NAME/refs\/heads\//}
          git push -f origin HEAD:$CLEAN_BRANCH_NAME
  

  lint_test_type_check:
    name: Lint, Test, Coverage, and Type Checking
    needs: format_code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Fetch latest commit SHA
        id: fetch-latest-sha
        run: |
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
          echo "Branch name: $BRANCH_NAME"
          LATEST_SHA=$(git rev-parse origin/"$BRANCH_NAME")
          echo "Latest SHA: $LATEST_SHA"
          echo "LATEST_SHA=$LATEST_SHA" >> $GITHUB_ENV

      - name: Checkout the latest commit
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.fetch-latest-sha.outputs.sha }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 

      - name: Lint with flake8
        id: flake8
        run: |
          flake8 .
        continue-on-error: true

      - name: Test coverage
        id: coverage
        run: |
          coverage run --rcfile=.github/.coveragerc
          coverage report --rcfile=.github/.coveragerc
          coverage json --rcfile=.github/.coveragerc
          echo "coverage_percentage=$(jq -r '.totals.percent_covered_display' .github/workflows/coverage.json)" >> $GITHUB_OUTPUT
          echo "coverage_percentage=$(jq -r '.totals.percent_covered_display' .github/workflows/coverage.json)"
        continue-on-error: true

      - name: Run mypy on the current branch
        run: |
          python -m mypy . 2>&1 | tee mypy_current_branch_report.txt || true
          grep -c "error:" mypy_current_branch_report.txt > mypy_current_branch_error_count.txt

      - name: Set current branch error count as output
        id: set_current_branch_error_count
        run: echo "error_count=$(cat mypy_current_branch_error_count.txt)" >> $GITHUB_OUTPUT

      - name: Extract mypy error count from README
        if: github.ref != 'refs/heads/main'
        run: |
          git checkout main
          # Use awk to match and extract only the first set of digits before any non-digit characters
          error_count=$(awk -F'-' '/Mypy/{match($2, /[0-9]+/); print substr($2, RSTART, RLENGTH)}' README.md)
          if [ -z "$error_count" ]; then
            echo "Error count not found in README.md"
            exit 1
          fi
          echo "Mypy error count on main branch: $error_count"
          echo $error_count > mypy_main_branch_error_count.txt
      - name: Set main branch error count as output
        id: set_main_branch_error_count
        if: github.ref != 'refs/heads/main'
        run: echo "error_count=$(cat mypy_main_branch_error_count.txt)" >> $GITHUB_OUTPUT

      - name: Compare mypy reports
        if: github.ref != 'refs/heads/main'
        run: |
          CURRENT_ERRORS=${{ steps.set_current_branch_error_count.outputs.error_count }}
          MAIN_ERRORS=${{ steps.set_main_branch_error_count.outputs.error_count }}
          echo "Current branch mypy errors: $CURRENT_ERRORS"
          echo "Main branch mypy errors: $MAIN_ERRORS"
          if [ $CURRENT_ERRORS -gt $MAIN_ERRORS ]; then
            echo "Mypy error count has increased from the main branch to the current branch ($MAIN_ERRORS -> $CURRENT_ERRORS)."
            exit 1
          else
            echo "No increase in mypy errors found."
          fi
        continue-on-error: true

      - name: Checkout current branch
        if: github.ref != 'refs/heads/main'
        run: git checkout ${{ github.head_ref }}

      - name: Set color and status for Flake8 badge
        id: flake8_status
        run: |
          if [ ${{ steps.flake8.outcome }} == 'success' ] ; then
            echo "flake8_badge_color=brightgreen" >> $GITHUB_OUTPUT
            echo "flake8_badge_status=passed" >> $GITHUB_OUTPUT
          else
            echo "flake8_badge_color=red" >> $GITHUB_OUTPUT
            echo "flake8_badge_status=failed" >> $GITHUB_OUTPUT
          fi

      - name: Set color and status for Pytest badge
        id: pytest_status
        run: |
          if [ ${{ steps.coverage.outcome }} == 'success' ]; then
            echo "pytest_badge_color=brightgreen" >> $GITHUB_OUTPUT
            echo "pytest_badge_status=passed" >> $GITHUB_OUTPUT
          else
            echo "pytest_badge_color=red" >> $GITHUB_OUTPUT
            echo "pytest_badge_status=failed" >> $GITHUB_OUTPUT
          fi

      - name: Update Badges
        run: |
          flake8_badge_url="https://img.shields.io/badge/Flake8-${{ steps.flake8_status.outputs.flake8_badge_status }}-${{ steps.flake8_status.outputs.flake8_badge_color }}"
          flake8_badge_markdown_str="[![Flake8](${flake8_badge_url})]"
          sed -i "s|\[\!\[Flake8\]\(.*\)\]|${flake8_badge_markdown_str}|" ./README.md
          
          pytest_badge_url="https://img.shields.io/badge/Pytest-${{ steps.pytest_status.outputs.pytest_badge_status }}-${{ steps.pytest_status.outputs.pytest_badge_color }}"
          pytest_badge_markdown_str="[![Pytest](${pytest_badge_url})]"
          sed -i "s|\[\!\[Pytest\]\(.*\)\]|${pytest_badge_markdown_str}|" ./README.md
          
          chmod +x ./.github/workflows/update_coverage_mypy_badges.sh
          ./.github/workflows/update_coverage_mypy_badges.sh

      - name: Commit & Push Badge Updates
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update badges on README"
          add: "README.md"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for Flake8 Errors
        if: ${{ steps.flake8.outcome == 'failure' }}
        run: |
          echo "Flake8 encountered errors. Please fix the linting error(s) in the Lint-with-flake8 step and re-run the workflow."
          exit 1

      - name: Check for Pytest Errors
        if: ${{ steps.coverage.outcome == 'failure' }}
        run: |
          echo "Pytest encountered errors. Please fix the error(s) in the Test-Coverage step and re-run the workflow."
          exit 1

      - name: Comment on Coverage and Mypy Errors
        env:
          URL: ${{ github.event.pull_request.comments_url }}
        run: |
          MY_ERROR_COUNT=${{ steps.set_current_branch_error_count.outputs.error_count }}
          MAIN_ERRORS=${{ steps.set_main_branch_error_count.outputs.error_count }}
          if [ -n "$URL" ]; then
            PYTEST_COVERAGE="Current Coverage: ${{ steps.coverage.outputs.coverage_percentage }}%"
            echo "$PYTEST_COVERAGE"
            MYPY_ERRORS="Mypy errors on ${{ github.head_ref }} branch: $MY_ERROR_COUNT"
            MYPY_ERRORS="$MYPY_ERRORS\nMypy errors on main branch: $MAIN_ERRORS"
            DIFF=$((MY_ERROR_COUNT - MAIN_ERRORS))
            if [ $DIFF -gt 0 ]; then
              MYPY_ERRORS="$MYPY_ERRORS\n$DIFF more errors on ${{ github.head_ref }} branch"
            elif [ $DIFF -lt 0 ]; then
              DIFF=$((DIFF * -1))
              MYPY_ERRORS="$MYPY_ERRORS\n$DIFF fewer errors on ${{ github.head_ref }} branch"
            else
              MYPY_ERRORS="$MYPY_ERRORS\nNo difference in error counts"
            fi
            echo "$MYPY_ERRORS"
            COMMIT_MESSAGE="$PYTEST_COVERAGE\n\n$MYPY_ERRORS"
            echo "$COMMIT_MESSAGE"
            curl \
              -X POST \
              $URL \
              -H "Content-Type: application/json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              --data "{\"body\": \"$COMMIT_MESSAGE\"}"
          fi
