# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test and Coverage

on:
  workflow_dispatch:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # Environment setup
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # https://coverage.readthedocs.io/en/7.2.7/index.html
    # Run coverage test, Generate report, Save to JSON file, Set COVERAGE_PERCENTAGE extracted from JSON
    # A configuration file ".coveragerc" can be found in .github/ to customize coverage test settings
    - name: Test coverage
      run: |
        coverage run --rcfile=.github/.coveragerc
        coverage report --rcfile=.github/.coveragerc
        coverage json --rcfile=.github/.coveragerc
        echo "COVERAGE_PERCENTAGE=$( jq -r '.totals.percent_covered_display' ./.github/workflows/coverage.json )" >> "$GITHUB_ENV"
        echo "${{ env.COVERAGE_PERCENTAGE }}"

    # Generate a Shields.io static badge and update README.md coverage badge link
    - name: Update Coverage Badge
      run:
        ./.github/workflows/update_badge.sh

    # Update repository
    # https://github.com/marketplace/actions/github-commit-push
    - name: Commit & Push changes to Readme
      uses: actions-js/push@master
      with:
        message: Update coverage on Readme
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}

    # Post a comment to current PR with the updated coverage
    - name: Comment Coverage
      env:
        URL: ${{ github.event.pull_request.comments_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ ${{ env.URL }} != '' ]; then
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "Current Coverage: ${{ env.COVERAGE_PERCENTAGE }}%" }'
        fi
