name: Type Checking with Mypy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run mypy
        run: |
          python -m mypy --install-types --non-interactive --strict RUFAS tests main.py setup.py > ../mypy_report.txt 2>&1 || true

      - name: Update Mypy badge
        run: |
          ./.github/workflows/update_mypy_badge.sh

      - name: Commit & Push changes to README
        uses: EndBug/add-and-commit@v7
        with:
          message: "Update mypy badge on README"
          add: "README.md ../mypy_report.txt"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}

      - name: Post a comment to current PR with the updated mypy report
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MYPY_ERROR_COUNT: $(grep -c "error:" ../mypy_report.txt)
        run: |
          if [ -n ${{ env.URL }} ]; then
            curl \
              -X POST \
              $URL \
              -H "Authorization: token ${{ env.GITHUB_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d "{\"body\": \"Mypy found ${{ env.MYPY_ERROR_COUNT }} errors. [Mypy Report](../mypy_report.txt)\"}" ${{ env.URL }}
          fi
