from __future__ import annotations

from dataclasses import dataclass
from typing import Dict
from typing import List
from typing import Optional
from typing import Tuple
from typing import Type
from typing import Union

import math

from RUFAS.routines.manure.default_enum.default_enum import DefaultEnum
from RUFAS.routines.manure.gas_emissions.gas_emissions import GasEmissions
from RUFAS.routines.manure.manure_handlers.manure_handler_daily_output import ManureHandlerDailyOutput
from RUFAS.routines.manure.manure_separators.manure_separator_daily_output import ManureSeparatorDailyOutput
from RUFAS.routines.manure.manure_treatments.manure_treatment_daily_output import ManureTreatmentDailyOutput
from RUFAS.routines.manure.manure_treatments.manure_treatment_daily_output import SludgeOutput
from RUFAS.routines.manure.reception_pits.reception_pit_daily_output import ReceptionPitDailyOutput

# Tne input for a manure treatment can come from a reception pit or a manure separator.
ManureTreatmentInputDataType = Union[ReceptionPitDailyOutput, ManureSeparatorDailyOutput]


class ManureTreatmentType(DefaultEnum):
    """Enumerates the different types of manure treatments."""
    SLURRY_STORAGE_UNDERFLOOR = 'slurry storage underfloor'
    SLURRY_STORAGE_OUTDOOR = 'slurry storage outdoor'
    ANAEROBIC_LAGOON = 'anaerobic lagoon'
    DEFAULT = SLURRY_STORAGE_UNDERFLOOR


class BaseManureTreatment:
    """Base class for all manure treatment classes.

    Attributes:
        weather: A Weather object.
        time: A Time object.
        config: A ManureTreatmentConfig object containing the configuration for the manure treatment.
        all_output: A list of ManureTreatmentDailyOutput objects containing the output for each day of the simulation.

    """

    def __init__(self, weather, time, manure_treatment_config: ManureTreatmentConfig) -> None:
        """Initializes the BaseManureTreatment class.

        Args:
            weather: A Weather object.
            time: A Time object.
            manure_treatment_config: A ManureTreatmentConfig object containing the
                configuration for the manure treatment.

        Private attributes:
            _current_input_data: The current input data assigned based on the
                input data passed into the daily_update() method.

        """
        self.weather = weather
        self.time = time
        self._sim_day = -1
        self._manure_handler_daily_output = None
        self.config = manure_treatment_config
        self.all_output: List[ManureTreatmentDailyOutput] = []
        self._current_input_data: Optional[ManureTreatmentInputDataType] = None

    @property
    def last_output(self) -> Optional[ManureTreatmentDailyOutput]:
        """Return the last daily output data generated by the last call to daily_update().

        Returns:
            The last daily output data generated by the last call to daily_update().
            None if daily_update() has not been called yet.

        """
        return self.all_output[-1] if len(self.all_output) > 0 else None

    def _update_helper(self) -> ManureTreatmentDailyOutput:
        """Decide how to process the input data passed into the daily_update() method.

        Returns:
            A ManureTreatmentDailyOutput object containing the output for the
                current simulation day.

        """
        input_data = self._current_input_data
        daily_output = ManureTreatmentDailyOutput(
                simulation_day=input_data.simulation_day,
                pen_id=input_data.pen_id,
                TAN=input_data.TAN * (1 - self.config.TAN_removal_efficiency_for_treatment),
                N=input_data.N * (1 - self.config.N_removal_efficiency_for_treatment),
                TS=input_data.TS * (1 - self.config.TS_removal_efficiency_for_treatment),
                VS_total=input_data.VS_total * (1 - self.config.VS_removal_efficiency_for_treatment),
                P=input_data.P * (1 - self.config.P_removal_efficiency_for_treatment),
                K=input_data.K * (1 - self.config.K_removal_efficiency_for_treatment),
        )
        self._adjust_final_manure_volume(daily_output)
        return daily_output

    def _get_input_manure_volume(self) -> float:
        if isinstance(self._current_input_data, ManureSeparatorDailyOutput):
            return self._current_input_data.final_daily_volume
        else:
            return self._current_input_data.total_daily_manure_volume

    def _adjust_final_manure_volume(self, daily_manure_treatment_output: ManureTreatmentDailyOutput):
        daily_manure_treatment_output.final_daily_volume = self._get_input_manure_volume()
        daily_manure_treatment_output.final_manure_volume -= \
            (self._current_input_data.TS - daily_manure_treatment_output.TS) / 1000.0

    def daily_update(self,
                     manure_handler_daily_output: ManureHandlerDailyOutput,
                     reception_pit_daily_output: ReceptionPitDailyOutput,
                     manure_separator_daily_output: Optional[ManureSeparatorDailyOutput],
                     sim_day: int
                     ) -> ManureTreatmentDailyOutput:
        """Calculate and store the daily output of the manure treatment.

        Args:
            reception_pit_daily_output: ReceptionPitDailyOutput object containing
                the daily output of the reception pit.
            manure_separator_daily_output: ManureSeparatorDailyOutput object containing
                the daily output of the manure separator.
            sim_day: The current simulation day.

        Returns:
            A ManureTreatmentDailyOutput object containing the output of the manure
                treatment for the current simulation day.

        """
        self._sim_day = sim_day
        self._manure_handler_daily_output = manure_handler_daily_output
        self._current_input_data = manure_separator_daily_output or reception_pit_daily_output
        daily_output = self._update_helper()
        self.all_output.append(daily_output)
        return daily_output


class SlurryStorageUnderfloor(BaseManureTreatment):
    """Class for the underfloor slurry storage.

    Attributes:
        All attributes inherited from BaseManureTreatment.
        In addition, the following attributes are defined:
        storage_time_period: Time in days that the manure is stored in the manure
            treatment system, days.

    """

    def __init__(self, weather, time, manure_treatment_config: ManureTreatmentConfig) -> None:
        """Initialize the underfloor slurry storage manure treatment.

        Args:
            weather: A Weather object.
            time: A Time object.
            manure_treatment_config: A ManureTreatmentConfig object containing
                the configuration data for the manure treatment system.

        """
        super().__init__(weather, time, manure_treatment_config)
        self.storage_time_period = self.config.storage_time_period


class SlurryStorageOutdoor(BaseManureTreatment):
    """Class for the outdoor slurry storage.

    Attributes:
        All attributes inherited from BaseManureTreatment.
        In addition, the following attributes are defined:
        storage_time_period: Time in days that the manure is stored in the manure
            treatment system, days.
        freeboard_input: Empty storage space above the manure in the treatment system.
        precip_input: Storage space for the amount of precipitation that falls
            onto the treatment system.

    """

    def __init__(self, weather, time, manure_treatment_config: ManureTreatmentConfig) -> None:
        """Initialize the outdoor slurry storage manure treatment.

        Args:
            weather: A Weather object.
            time: A Time object.
            manure_treatment_config: A ManureTreatmentConfig object containing
                the configuration data for the manure treatment system.
        """

        super().__init__(weather, time, manure_treatment_config)
        self.storage_time_period = self.config.storage_time_period
        self.freeboard_input = self.config.freeboard_input
        self.precip_input = self.config.precip_input

    @property
    def wastewater_volume(self) -> float:
        """Calculate the volume of wastewater in the treatment system.

        Returns:
            The volume of wastewater in the treatment system, m^3.

        """
        if self._current_input_data:
            return self._current_input_data.total_daily_manure_volume
        return 0.0

    @property
    def treatment_volume(self) -> float:
        """Calculate the minimum treatment volume.

        Returns:
            The minimum treatment volume, m^3.

        """
        if self._current_input_data:
            return self._current_input_data.total_daily_manure_volume * self.storage_time_period  # m^3
        return 0.0

    @property
    def total_pit_volume(self) -> float:
        """Calculate the total pit volume.

        Returns:
            The total lagoon pit, m^3.

        """
        if self._current_input_data:
            return self.treatment_volume + self.freeboard + self.precip
        return 0.0

    @property
    def pit_depth(self):
        """Return the depth of the pit.

        Returns:
            The depth of the pit, m.

        """
        return 3.657

    @property
    def pit_slope(self):
        """Return the slope of the pit.

        Returns:
            The slope of the pit, dimensionless.

        """
        return 2.0

    def _calc_abc(self) -> Tuple[float, float, float]:
        """Calculate the coefficients a, b, and c for volume calculations.

        Returns:
            A tuple containing the coefficients a, b, and c for volume calculations.

        """
        a = 3 * self.pit_depth
        b = -4 * self.pit_slope * self.pit_depth ** 2
        c = 4 * (self.pit_slope ** 2) * (self.pit_depth ** 3) / 3 - self.treatment_volume
        return a, b, c

    @property
    def pit_width(self) -> float:
        """Calculate the width of the pit.

        Returns:
            The width of the pit, m.

        """
        if self._current_input_data:
            a, b, c = self._calc_abc()
            return (-b + math.sqrt(b ** 2 - 4 * a * c)) / (2 * a)
        return 0.0

    @property
    def pit_length(self) -> float:
        """Calculate the length of the pit.

        Returns:
            The length of the pit, m.

        """
        return self.pit_width * 3

    @property
    def pit_surface_area(self) -> float:
        """Calculate the surface area of the pit.

        Returns:
            The surface area of the pit, m^2.

        """
        return self.pit_width * self.pit_length

    @property
    def pit_volume(self) -> float:
        """Calculate the volume of the pit.

        Returns:
            The volume of the pit, m^3.

        """
        return self.pit_length * self.pit_width * self.pit_depth \
               - (self.pit_slope * (self.pit_depth ** 2)) * (self.pit_length + self.pit_width) \
               + (4 * self.pit_slope * (self.pit_depth ** 3) / 3)

    @property
    def precip(self) -> float:
        """Calculate the additional pit volume needed for precipitation.

        Returns:
            The additional pit volume needed for precipitation, m^3.

        """
        current_day_rainfall = self.weather.rainfall[self.time.year - 1][self.time.day - 1]
        return current_day_rainfall * self.pit_surface_area

    @property
    def freeboard(self):
        """Calculate the additional pit volume needed for freeboard.

        Returns:
            The additional pit volume needed for freeboard, m^3.

        """
        return self.freeboard_input * self.pit_surface_area


class AnaerobicLagoon(BaseManureTreatment):
    def __init__(self,
                 weather,
                 time,
                 manure_treatment_config: ManureTreatmentConfig):
        super().__init__(weather, time, manure_treatment_config)
        self.storage_time_period = self.config.storage_time_period  # days
        self.freeboard_input = self.config.freeboard_input  # m
        self._accumulated_sludge_output = SludgeOutput()
        self._accumulated_minimum_treatment_volume = 0.0
        self._accumulated_precip = 0.0

    def _update_helper(self):
        input_data = self._current_input_data
        daily_output = ManureTreatmentDailyOutput(
                TAN=input_data.TAN * (1 - self.config.TAN_removal_efficiency_for_treatment),
                N=input_data.N * (1 - self.config.N_removal_efficiency_for_treatment),
                TS=input_data.TS * (1 - self.config.TS_removal_efficiency_for_treatment),
                VS_total=input_data.VS_total * (1 - self.config.VS_removal_efficiency_for_treatment),
                P=input_data.P * (1 - self.config.P_removal_efficiency_for_treatment),
                K=input_data.K * (1 - self.config.K_removal_efficiency_for_treatment),
        )
        self._adjust_final_manure_volume(daily_output)
        self._accumulate_minimum_treatment_volume()
        self._accumulate_precip()

        sludge_output = SludgeOutput(
                TS=input_data.TS * self.config.TS_removal_efficiency_for_treatment,
                VS=input_data.VS_total * self.config.VS_removal_efficiency_for_treatment,
                N=input_data.N * self.config.N_removal_efficiency_for_treatment,
                P=input_data.P * self.config.P_removal_efficiency_for_treatment,
                K=input_data.K * self.config.K_removal_efficiency_for_treatment
        )
        self._accumulated_sludge_output += sludge_output

        daily_output.sludge_TS = sludge_output.TS
        daily_output.sludge_VS = sludge_output.VS
        daily_output.sludge_N = sludge_output.N
        daily_output.sludge_P = sludge_output.P
        daily_output.sludge_K = sludge_output.K
        daily_output.accumulated_sludge_TS = self._accumulated_sludge_output.TS
        daily_output.accumulated_minimum_treatment_volume = self._accumulated_minimum_treatment_volume

        return daily_output

    def _adjust_final_manure_volume(self, daily_manure_treatment_output: ManureTreatmentDailyOutput):
        super()._adjust_final_manure_volume(daily_manure_treatment_output)
        daily_manure_treatment_output.final_manure_volume += self.precip
        if self._sim_day % self.storage_time_period > 1:
            daily_manure_treatment_output.final_manure_volume -= self.flushing_volume

    @property
    def sludge_accumulation_volume(self):
        """Returns sludge accumulation volume in m^3
        """
        return self._accumulated_sludge_output.TS / 1000

    @property
    def flushing_volume(self):
        """returns flushing water recycled in m^3"""
        return self._manure_handler_daily_output.cleaning_water_volume

    @property
    def wastewater_volume(self):
        """Calculate the volume of wastewater in the treatment system.

        Returns:
            The volume of wastewater in the treatment system, m^3.

        """
        return self._get_input_manure_volume()

    @property
    def reduced_volume(self):
        """returns reduced volume in m^3"""
        return self.wastewater_volume - self.flushing_volume  # m^3

    def _accumulate_minimum_treatment_volume(self) -> float:
        """returns minimum treatment volume in m^3"""
        if self._sim_day % self.storage_time_period == 1:
            self._accumulated_minimum_treatment_volume = self._get_input_manure_volume()
        else:
            self._accumulated_minimum_treatment_volume += self.reduced_volume
        return self._accumulated_minimum_treatment_volume

    @property
    def total_lagoon_volume(self) -> float:
        """returns Total Lagoon Volume in m^3. The precipitation is already included in volume_needed"""
        return self.volume_needed + self.freeboard + self._accumulated_precip

    @property
    def volume_needed(self):
        """returns volume needed for lagoon sizing in m^3"""
        return self._accumulated_minimum_treatment_volume + self.sludge_accumulation_volume

    @property
    def lagoon_depth(self):
        """returns lagoon depth in meters"""
        return 3.657  # meters

    @property
    def lagoon_slope(self):
        """returns lagoon slope (unitless)"""
        return 2.0

    def calc_abc(self):
        """returns coefficients for volume calculations as tuple (a,b,c)"""
        a = 3 * self.lagoon_depth
        b = -4 * self.lagoon_slope * self.lagoon_depth ** 2
        c = 4 * (self.lagoon_slope ** 2) * (self.lagoon_depth ** 3) / 3 - self.volume_needed
        return a, b, c

    @property
    def lagoon_width(self):
        """returns lagoon width in meters"""
        abc = self.calc_abc()
        a, b, c = abc[0], abc[1], abc[2]
        return (-1 * b + (b ** 2 - 4 * a * c) ** 0.5) / (2 * a)

    @property
    def lagoon_length(self):
        """returns lagoon width in meters"""
        return self.lagoon_width * 3

    @property
    def lagoon_surface_area(self):
        """returns lagoon surface area in m^2"""
        return self.lagoon_width * self.lagoon_length

    @property
    def modeled_lagoon_volume(self):
        """returns modeled lagoon volume in m^3. This modeled volume is used to verify
        that equations for surface area, with slope assumptions, match the volume needed for treatment"""
        return self.lagoon_length * self.lagoon_width * self.lagoon_depth \
               - (self.lagoon_slope * self.lagoon_depth ** 2) * (self.lagoon_length + self.lagoon_width) \
               + 4 * self.lagoon_slope * self.lagoon_depth ** 3 / 3

    @property
    def precip(self):
        """returns additional lagoon volume needed for precipitation in m^3"""
        current_day_rainfall = self.weather.rainfall[self.time.year - 1][self.time.day - 1]
        return current_day_rainfall * self.lagoon_surface_area  # m3 of rain

    def _accumulate_precip(self):
        self._accumulated_precip += self.precip

    @property
    def freeboard(self):
        """returns additional lagoon volume needed for freeboard in m^3"""
        return self.freeboard_input * self.lagoon_surface_area  # m3 of rain

    # def calc_emissions(self):
    #     return GasEmissions.calc_E_CH4_anaerobic_lagoon(self.accumulated_output.VS_total)

    def boundSludgeValue(self, calculated_value, lower_bound, upper_bound):
        """returns value bounded by lower and upper bounds"""
        return min(max(self.sludge_accumulation_volume * lower_bound, calculated_value),
                   self.sludge_accumulation_volume * upper_bound)


@dataclass
class ManureTreatmentConfig:
    """Class for storing manure treatment configuration data.

    Attributes:
        TS_removal_efficiency_for_treatment: Percent of total solids removed from manure during treatment.
        VS_removal_efficiency_for_treatment: Percent of volatile solids removed from manure during treatment.
        N_removal_efficiency_for_treatment: Percent of nitrogen removed from manure during treatment.
        TAN_removal_efficiency_for_treatment: Percent of total ammoniacal nitrogen removed from manure during treatment.
        P_removal_efficiency_for_treatment: Percent of phosphorus removed from manure during treatment.
        K_removal_efficiency_for_treatment: Percent of potassium removed from manure during treatment.

        hydraulic_retention_time: Time in days spent in the treatment system.
        sludge_accumulation_period: Time in days/years that sludge accumulates in the treatment system.
        SAV_fraction: Sludge Accumulation Volume (SAV) fraction based on the manure solids
            entering the treatment system.
        top_cover_volume_fraction: Fraction of the total volume of the treatment system
            that is assumed to be the top cover volume.
        biogas_gen_ratio: Amount of biogas generated from the treatment system.
        methane_gen_ratio: Amount of methane generated from the treatment system
            (calculated from the amount of biogas generated).
        evaporation_fraction: Fraction of the liquid portion evaporated from the treatment system.
        AD_temp_set_point: Temperature set point for the anaerobic digestion.
        AD_temp: Temperature of the anaerobic digestion.

        storage_time_period: Time in days that manure is stored in the treatment system.
        precip_input: Storage space for the amount of precipitation that falls onto the treatment system.
        freeboard_input: Empty storage space above the manure in the treatment system.

    """
    TS_removal_efficiency_for_treatment: float = 0.0
    VS_removal_efficiency_for_treatment: float = 0.0
    N_removal_efficiency_for_treatment: float = 0.0
    TAN_removal_efficiency_for_treatment: float = 0.0
    P_removal_efficiency_for_treatment: float = 0.0
    K_removal_efficiency_for_treatment: float = 0.0

    hydraulic_retention_time: int = 0
    sludge_accumulation_period: float = 0.0
    SAV_fraction: float = 0.0
    top_cover_volume_fraction: float = 0.0
    biogas_gen_ratio: float = 0.0
    methane_gen_ratio: float = 0.0

    evaporation_fraction: float = 0.0
    AD_temp_set_point: float = 0.0
    AD_temp: float = 0.0

    storage_time_period: int = 0,
    precip_input: float = 0.0,
    freeboard_input: float = 0.0


class DefaultManureTreatmentConfigFactory:
    """Class for creating default manure treatment configuration data."""

    SLURRY_STORAGE_UNDERFLOOR_CONFIG = ManureTreatmentConfig(
            TS_removal_efficiency_for_treatment=0.10,  # Between 10-30%
            VS_removal_efficiency_for_treatment=0.20,  # Between 20-40%
            N_removal_efficiency_for_treatment=0.10,  # # Between 10-30%
            TAN_removal_efficiency_for_treatment=0.45,  # Between 61-80%
            P_removal_efficiency_for_treatment=0.05,  # # Between 5-30%
            K_removal_efficiency_for_treatment=0.05,  # # Between 5-30%
            storage_time_period=120,
    )

    SLURRY_STORAGE_OUTDOOR_CONFIG = ManureTreatmentConfig(
            TS_removal_efficiency_for_treatment=0.10,  # Between 10-30%
            VS_removal_efficiency_for_treatment=0.20,  # Between 20-40%
            N_removal_efficiency_for_treatment=0.10,  # # Between 10-30%
            TAN_removal_efficiency_for_treatment=0.45,  # Between 61-80%
            P_removal_efficiency_for_treatment=0.05,  # # Between 5-30%
            K_removal_efficiency_for_treatment=0.05,  # # Between 5-30%
            storage_time_period=120,
            precip_input=0.0,
            freeboard_input=0.3048
    )

    @classmethod
    def get_instance(cls, treatment_type: ManureTreatmentType) -> ManureTreatmentConfig:
        """Return a default manure treatment configuration data instance for the given treatment type.

        Args:
            treatment_type: The type of manure treatment.

        Returns:
            A default manure treatment configuration data instance for the given treatment type.

        """
        manure_treatment_config_by_type = {
            ManureTreatmentType.SLURRY_STORAGE_UNDERFLOOR: cls.SLURRY_STORAGE_UNDERFLOOR_CONFIG,
            ManureTreatmentType.SLURRY_STORAGE_OUTDOOR: cls.SLURRY_STORAGE_OUTDOOR_CONFIG,
        }
        return manure_treatment_config_by_type[treatment_type]


class ManureTreatmentFactory:
    """Class for creating different types of manure treatment systems."""

    @staticmethod
    def get_instance(manure_treatment_type_name: str,
                     weather,
                     time,
                     custom_manure_treatment_config: Optional[ManureTreatmentConfig] = None) \
            -> BaseManureTreatment:
        """Return a manure treatment system instance for the given manure treatment type name.

        Args:
            manure_treatment_type_name: The name of the manure treatment type.
            weather: The weather data.
            time: The time data.
            custom_manure_treatment_config: The custom manure treatment configuration data.

        Returns:
            A manure treatment system instance for the given manure treatment type name.

        """

        manure_treatment_class_by_type: Dict[ManureTreatmentType, Type[BaseManureTreatment]] = {
            ManureTreatmentType.SLURRY_STORAGE_UNDERFLOOR: SlurryStorageUnderfloor,
            ManureTreatmentType.SLURRY_STORAGE_OUTDOOR: SlurryStorageOutdoor,
            ManureTreatmentType.ANAEROBIC_LAGOON: AnaerobicLagoon,
        }

        manure_treatment_type = ManureTreatmentType.get_type(manure_treatment_type_name)
        manure_treatment_class = manure_treatment_class_by_type[manure_treatment_type]

        if custom_manure_treatment_config:
            return manure_treatment_class(weather, time, custom_manure_treatment_config)
        else:
            default_manure_treatment_config = DefaultManureTreatmentConfigFactory.get_instance(manure_treatment_type)
            return manure_treatment_class(weather, time, default_manure_treatment_config)
